// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironflow/v1/deployment.proto

package ironflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FunctionRoutingMode is how a function selects the executable for new runs.
type FunctionRoutingMode int32

const (
	FunctionRoutingMode_FUNCTION_ROUTING_MODE_UNSPECIFIED FunctionRoutingMode = 0
	// Pre-ADR-0081 behavior: dispatch resolves the live function row. Every
	// function starts here.
	FunctionRoutingMode_FUNCTION_ROUTING_MODE_LEGACY FunctionRoutingMode = 1
	// Adoption in progress. A dispatch barrier holds while already-issued
	// executions drain.
	FunctionRoutingMode_FUNCTION_ROUTING_MODE_ADOPTING FunctionRoutingMode = 2
	// Every new run is pinned to the active deployment at creation.
	FunctionRoutingMode_FUNCTION_ROUTING_MODE_VERSIONED FunctionRoutingMode = 3
)

// Enum value maps for FunctionRoutingMode.
var (
	FunctionRoutingMode_name = map[int32]string{
		0: "FUNCTION_ROUTING_MODE_UNSPECIFIED",
		1: "FUNCTION_ROUTING_MODE_LEGACY",
		2: "FUNCTION_ROUTING_MODE_ADOPTING",
		3: "FUNCTION_ROUTING_MODE_VERSIONED",
	}
	FunctionRoutingMode_value = map[string]int32{
		"FUNCTION_ROUTING_MODE_UNSPECIFIED": 0,
		"FUNCTION_ROUTING_MODE_LEGACY":      1,
		"FUNCTION_ROUTING_MODE_ADOPTING":    2,
		"FUNCTION_ROUTING_MODE_VERSIONED":   3,
	}
)

func (x FunctionRoutingMode) Enum() *FunctionRoutingMode {
	p := new(FunctionRoutingMode)
	*p = x
	return p
}

func (x FunctionRoutingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionRoutingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_deployment_proto_enumTypes[0].Descriptor()
}

func (FunctionRoutingMode) Type() protoreflect.EnumType {
	return &file_ironflow_v1_deployment_proto_enumTypes[0]
}

func (x FunctionRoutingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionRoutingMode.Descriptor instead.
func (FunctionRoutingMode) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{0}
}

// ExecutionSnapshot is the execution configuration frozen into a deployment.
//
// It holds only what changes how a run EXECUTES. Display metadata and operator
// pause state are deliberately absent: those may change without minting a new
// deployment, and pause still overrides dispatch of every deployment.
type ExecutionSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event and cron triggers. Array order is preserved.
	Triggers []*Trigger   `protobuf:"bytes,1,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Retry    *RetryConfig `protobuf:"bytes,2,opt,name=retry,proto3" json:"retry,omitempty"`
	// Per-run timeout in milliseconds.
	TimeoutMs   int32              `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Concurrency *ConcurrencyConfig `protobuf:"bytes,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	CancelOn    []*CancelOnSpec    `protobuf:"bytes,5,rep,name=cancel_on,json=cancelOn,proto3" json:"cancel_on,omitempty"`
	Debounce    *DebounceConfig    `protobuf:"bytes,6,opt,name=debounce,proto3" json:"debounce,omitempty"`
	// Step-related and execution metadata carried verbatim.
	Metadata      *structpb.Struct `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionSnapshot) Reset() {
	*x = ExecutionSnapshot{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSnapshot) ProtoMessage() {}

func (x *ExecutionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSnapshot.ProtoReflect.Descriptor instead.
func (*ExecutionSnapshot) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionSnapshot) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *ExecutionSnapshot) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *ExecutionSnapshot) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecutionSnapshot) GetConcurrency() *ConcurrencyConfig {
	if x != nil {
		return x.Concurrency
	}
	return nil
}

func (x *ExecutionSnapshot) GetCancelOn() []*CancelOnSpec {
	if x != nil {
		return x.CancelOn
	}
	return nil
}

func (x *ExecutionSnapshot) GetDebounce() *DebounceConfig {
	if x != nil {
		return x.Debounce
	}
	return nil
}

func (x *ExecutionSnapshot) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Deployment is one immutable executable registration.
type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	FunctionId    string                 `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// Operator-chosen, case-sensitive, never reused: 1-128 ASCII letters,
	// digits, dots, underscores or hyphens, starting with a letter or digit.
	DeploymentId string `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// The operator's claim about the complete executable artifact, "sha256:"
	// plus 64 lowercase hex digits.
	//
	// It is a declaration, not remote attestation. Ironflow can check that a
	// worker advertises this digest; it cannot prove the process runs it.
	ArtifactDigest string             `protobuf:"bytes,4,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	Snapshot       *ExecutionSnapshot `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Mode           ExecutionMode      `protobuf:"varint,6,opt,name=mode,proto3,enum=ironflow.v1.ExecutionMode" json:"mode,omitempty"`
	// Push endpoint. Required for push mode, empty for pull.
	EndpointUrl   string                 `protobuf:"bytes,7,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *Deployment) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *Deployment) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *Deployment) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Deployment) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *Deployment) GetSnapshot() *ExecutionSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Deployment) GetMode() ExecutionMode {
	if x != nil {
		return x.Mode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *Deployment) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *Deployment) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Deployment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterDeploymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FunctionId     string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	DeploymentId   string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ArtifactDigest string                 `protobuf:"bytes,3,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	Snapshot       *ExecutionSnapshot     `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Mode           ExecutionMode          `protobuf:"varint,5,opt,name=mode,proto3,enum=ironflow.v1.ExecutionMode" json:"mode,omitempty"`
	EndpointUrl    string                 `protobuf:"bytes,6,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	// The ExecutionSnapshot schema this client was built against.
	//
	// The deployment's identity is computed from the snapshot the SERVER
	// decodes. ConnectRPC's JSON codec discards fields the server does not know,
	// so a newer client's execution setting is gone before the handler runs: the
	// canonical snapshot would match the stored one and the registration would
	// report created=false, leaving a deployment id that no longer identifies
	// the configuration the operator registered.
	//
	// Stating the version is what survives that discard, because this is a field
	// the server knows. A server rejects a version above its own rather than
	// storing an identity it cannot faithfully represent. 0 means a client older
	// than this field, which cannot be sending a later schema's fields either.
	SnapshotSchemaVersion int32 `protobuf:"varint,7,opt,name=snapshot_schema_version,json=snapshotSchemaVersion,proto3" json:"snapshot_schema_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterDeploymentRequest) Reset() {
	*x = RegisterDeploymentRequest{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeploymentRequest) ProtoMessage() {}

func (x *RegisterDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeploymentRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeploymentRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *RegisterDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RegisterDeploymentRequest) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *RegisterDeploymentRequest) GetSnapshot() *ExecutionSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *RegisterDeploymentRequest) GetMode() ExecutionMode {
	if x != nil {
		return x.Mode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *RegisterDeploymentRequest) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *RegisterDeploymentRequest) GetSnapshotSchemaVersion() int32 {
	if x != nil {
		return x.SnapshotSchemaVersion
	}
	return 0
}

type RegisterDeploymentResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Deployment *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// False when this call matched an existing identical registration. A worker
	// fleet rolling out one build re-registers on every boot.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeploymentResponse) Reset() {
	*x = RegisterDeploymentResponse{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeploymentResponse) ProtoMessage() {}

func (x *RegisterDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeploymentResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDeploymentResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *RegisterDeploymentResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentRequest) Reset() {
	*x = GetDeploymentRequest{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentRequest) ProtoMessage() {}

func (x *GetDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeploymentRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *GetDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type GetDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentResponse) Reset() {
	*x = GetDeploymentResponse{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentResponse) ProtoMessage() {}

func (x *GetDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeploymentResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsRequest) Reset() {
	*x = ListDeploymentsRequest{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsRequest) ProtoMessage() {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeploymentsRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *ListDeploymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeploymentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{7}
}

func (x *ListDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type GetFunctionExecutionRoutingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionExecutionRoutingRequest) Reset() {
	*x = GetFunctionExecutionRoutingRequest{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionExecutionRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionExecutionRoutingRequest) ProtoMessage() {}

func (x *GetFunctionExecutionRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionExecutionRoutingRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionExecutionRoutingRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{8}
}

func (x *GetFunctionExecutionRoutingRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

type GetFunctionExecutionRoutingResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FunctionId string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Mode       FunctionRoutingMode    `protobuf:"varint,2,opt,name=mode,proto3,enum=ironflow.v1.FunctionRoutingMode" json:"mode,omitempty"`
	// Empty unless mode is VERSIONED. A legacy function has no active
	// deployment, and none is ever inferred from configuration history.
	ActiveDeploymentId string `protobuf:"bytes,3,opt,name=active_deployment_id,json=activeDeploymentId,proto3" json:"active_deployment_id,omitempty"`
	// Monotonic per function. Pass it back as the expected revision on a routing
	// mutation so two racing callers produce one winner rather than a silent
	// last-write-wins.
	RoutingRevision int64 `protobuf:"varint,4,opt,name=routing_revision,json=routingRevision,proto3" json:"routing_revision,omitempty"`
	// Non-empty exactly while mode is ADOPTING.
	TransitionId        string                 `protobuf:"bytes,5,opt,name=transition_id,json=transitionId,proto3" json:"transition_id,omitempty"`
	TransitionStartedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=transition_started_at,json=transitionStartedAt,proto3" json:"transition_started_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetFunctionExecutionRoutingResponse) Reset() {
	*x = GetFunctionExecutionRoutingResponse{}
	mi := &file_ironflow_v1_deployment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionExecutionRoutingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionExecutionRoutingResponse) ProtoMessage() {}

func (x *GetFunctionExecutionRoutingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_deployment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionExecutionRoutingResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionExecutionRoutingResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_deployment_proto_rawDescGZIP(), []int{9}
}

func (x *GetFunctionExecutionRoutingResponse) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *GetFunctionExecutionRoutingResponse) GetMode() FunctionRoutingMode {
	if x != nil {
		return x.Mode
	}
	return FunctionRoutingMode_FUNCTION_ROUTING_MODE_UNSPECIFIED
}

func (x *GetFunctionExecutionRoutingResponse) GetActiveDeploymentId() string {
	if x != nil {
		return x.ActiveDeploymentId
	}
	return ""
}

func (x *GetFunctionExecutionRoutingResponse) GetRoutingRevision() int64 {
	if x != nil {
		return x.RoutingRevision
	}
	return 0
}

func (x *GetFunctionExecutionRoutingResponse) GetTransitionId() string {
	if x != nil {
		return x.TransitionId
	}
	return ""
}

func (x *GetFunctionExecutionRoutingResponse) GetTransitionStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TransitionStartedAt
	}
	return nil
}

func (x *GetFunctionExecutionRoutingResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_ironflow_v1_deployment_proto protoreflect.FileDescriptor

const file_ironflow_v1_deployment_proto_rawDesc = "" +
	"\n" +
	"\x1cironflow/v1/deployment.proto\x12\vironflow.v1\x1a\x17ironflow/v1/types.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x02\n" +
	"\x11ExecutionSnapshot\x120\n" +
	"\btriggers\x18\x01 \x03(\v2\x14.ironflow.v1.TriggerR\btriggers\x12.\n" +
	"\x05retry\x18\x02 \x01(\v2\x18.ironflow.v1.RetryConfigR\x05retry\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12@\n" +
	"\vconcurrency\x18\x04 \x01(\v2\x1e.ironflow.v1.ConcurrencyConfigR\vconcurrency\x126\n" +
	"\tcancel_on\x18\x05 \x03(\v2\x19.ironflow.v1.CancelOnSpecR\bcancelOn\x127\n" +
	"\bdebounce\x18\x06 \x01(\v2\x1b.ironflow.v1.DebounceConfigR\bdebounce\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x8b\x03\n" +
	"\n" +
	"Deployment\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\tR\n" +
	"functionId\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\x12'\n" +
	"\x0fartifact_digest\x18\x04 \x01(\tR\x0eartifactDigest\x12:\n" +
	"\bsnapshot\x18\x05 \x01(\v2\x1e.ironflow.v1.ExecutionSnapshotR\bsnapshot\x12.\n" +
	"\x04mode\x18\x06 \x01(\x0e2\x1a.ironflow.v1.ExecutionModeR\x04mode\x12!\n" +
	"\fendpoint_url\x18\a \x01(\tR\vendpointUrl\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd1\x02\n" +
	"\x19RegisterDeploymentRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12'\n" +
	"\x0fartifact_digest\x18\x03 \x01(\tR\x0eartifactDigest\x12:\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x1e.ironflow.v1.ExecutionSnapshotR\bsnapshot\x12.\n" +
	"\x04mode\x18\x05 \x01(\x0e2\x1a.ironflow.v1.ExecutionModeR\x04mode\x12!\n" +
	"\fendpoint_url\x18\x06 \x01(\tR\vendpointUrl\x126\n" +
	"\x17snapshot_schema_version\x18\a \x01(\x05R\x15snapshotSchemaVersion\"o\n" +
	"\x1aRegisterDeploymentResponse\x127\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x17.ironflow.v1.DeploymentR\n" +
	"deployment\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\\\n" +
	"\x14GetDeploymentRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"P\n" +
	"\x15GetDeploymentResponse\x127\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x17.ironflow.v1.DeploymentR\n" +
	"deployment\"g\n" +
	"\x16ListDeploymentsRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"T\n" +
	"\x17ListDeploymentsResponse\x129\n" +
	"\vdeployments\x18\x01 \x03(\v2\x17.ironflow.v1.DeploymentR\vdeployments\"E\n" +
	"\"GetFunctionExecutionRoutingRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\"\x89\x03\n" +
	"#GetFunctionExecutionRoutingResponse\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x124\n" +
	"\x04mode\x18\x02 \x01(\x0e2 .ironflow.v1.FunctionRoutingModeR\x04mode\x120\n" +
	"\x14active_deployment_id\x18\x03 \x01(\tR\x12activeDeploymentId\x12)\n" +
	"\x10routing_revision\x18\x04 \x01(\x03R\x0froutingRevision\x12#\n" +
	"\rtransition_id\x18\x05 \x01(\tR\ftransitionId\x12N\n" +
	"\x15transition_started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x13transitionStartedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xa7\x01\n" +
	"\x13FunctionRoutingMode\x12%\n" +
	"!FUNCTION_ROUTING_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFUNCTION_ROUTING_MODE_LEGACY\x10\x01\x12\"\n" +
	"\x1eFUNCTION_ROUTING_MODE_ADOPTING\x10\x02\x12#\n" +
	"\x1fFUNCTION_ROUTING_MODE_VERSIONED\x10\x032\xc2\x03\n" +
	"\x11DeploymentService\x12e\n" +
	"\x12RegisterDeployment\x12&.ironflow.v1.RegisterDeploymentRequest\x1a'.ironflow.v1.RegisterDeploymentResponse\x12[\n" +
	"\rGetDeployment\x12!.ironflow.v1.GetDeploymentRequest\x1a\".ironflow.v1.GetDeploymentResponse\"\x03\x90\x02\x01\x12a\n" +
	"\x0fListDeployments\x12#.ironflow.v1.ListDeploymentsRequest\x1a$.ironflow.v1.ListDeploymentsResponse\"\x03\x90\x02\x01\x12\x85\x01\n" +
	"\x1bGetFunctionExecutionRouting\x12/.ironflow.v1.GetFunctionExecutionRoutingRequest\x1a0.ironflow.v1.GetFunctionExecutionRoutingResponse\"\x03\x90\x02\x01B:Z8github.com/sahina/ironflow-go/api/ironflow/v1;ironflowv1b\x06proto3"

var (
	file_ironflow_v1_deployment_proto_rawDescOnce sync.Once
	file_ironflow_v1_deployment_proto_rawDescData []byte
)

func file_ironflow_v1_deployment_proto_rawDescGZIP() []byte {
	file_ironflow_v1_deployment_proto_rawDescOnce.Do(func() {
		file_ironflow_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironflow_v1_deployment_proto_rawDesc), len(file_ironflow_v1_deployment_proto_rawDesc)))
	})
	return file_ironflow_v1_deployment_proto_rawDescData
}

var file_ironflow_v1_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ironflow_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ironflow_v1_deployment_proto_goTypes = []any{
	(FunctionRoutingMode)(0),                    // 0: ironflow.v1.FunctionRoutingMode
	(*ExecutionSnapshot)(nil),                   // 1: ironflow.v1.ExecutionSnapshot
	(*Deployment)(nil),                          // 2: ironflow.v1.Deployment
	(*RegisterDeploymentRequest)(nil),           // 3: ironflow.v1.RegisterDeploymentRequest
	(*RegisterDeploymentResponse)(nil),          // 4: ironflow.v1.RegisterDeploymentResponse
	(*GetDeploymentRequest)(nil),                // 5: ironflow.v1.GetDeploymentRequest
	(*GetDeploymentResponse)(nil),               // 6: ironflow.v1.GetDeploymentResponse
	(*ListDeploymentsRequest)(nil),              // 7: ironflow.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),             // 8: ironflow.v1.ListDeploymentsResponse
	(*GetFunctionExecutionRoutingRequest)(nil),  // 9: ironflow.v1.GetFunctionExecutionRoutingRequest
	(*GetFunctionExecutionRoutingResponse)(nil), // 10: ironflow.v1.GetFunctionExecutionRoutingResponse
	(*Trigger)(nil),                             // 11: ironflow.v1.Trigger
	(*RetryConfig)(nil),                         // 12: ironflow.v1.RetryConfig
	(*ConcurrencyConfig)(nil),                   // 13: ironflow.v1.ConcurrencyConfig
	(*CancelOnSpec)(nil),                        // 14: ironflow.v1.CancelOnSpec
	(*DebounceConfig)(nil),                      // 15: ironflow.v1.DebounceConfig
	(*structpb.Struct)(nil),                     // 16: google.protobuf.Struct
	(ExecutionMode)(0),                          // 17: ironflow.v1.ExecutionMode
	(*timestamppb.Timestamp)(nil),               // 18: google.protobuf.Timestamp
}
var file_ironflow_v1_deployment_proto_depIdxs = []int32{
	11, // 0: ironflow.v1.ExecutionSnapshot.triggers:type_name -> ironflow.v1.Trigger
	12, // 1: ironflow.v1.ExecutionSnapshot.retry:type_name -> ironflow.v1.RetryConfig
	13, // 2: ironflow.v1.ExecutionSnapshot.concurrency:type_name -> ironflow.v1.ConcurrencyConfig
	14, // 3: ironflow.v1.ExecutionSnapshot.cancel_on:type_name -> ironflow.v1.CancelOnSpec
	15, // 4: ironflow.v1.ExecutionSnapshot.debounce:type_name -> ironflow.v1.DebounceConfig
	16, // 5: ironflow.v1.ExecutionSnapshot.metadata:type_name -> google.protobuf.Struct
	1,  // 6: ironflow.v1.Deployment.snapshot:type_name -> ironflow.v1.ExecutionSnapshot
	17, // 7: ironflow.v1.Deployment.mode:type_name -> ironflow.v1.ExecutionMode
	18, // 8: ironflow.v1.Deployment.created_at:type_name -> google.protobuf.Timestamp
	1,  // 9: ironflow.v1.RegisterDeploymentRequest.snapshot:type_name -> ironflow.v1.ExecutionSnapshot
	17, // 10: ironflow.v1.RegisterDeploymentRequest.mode:type_name -> ironflow.v1.ExecutionMode
	2,  // 11: ironflow.v1.RegisterDeploymentResponse.deployment:type_name -> ironflow.v1.Deployment
	2,  // 12: ironflow.v1.GetDeploymentResponse.deployment:type_name -> ironflow.v1.Deployment
	2,  // 13: ironflow.v1.ListDeploymentsResponse.deployments:type_name -> ironflow.v1.Deployment
	0,  // 14: ironflow.v1.GetFunctionExecutionRoutingResponse.mode:type_name -> ironflow.v1.FunctionRoutingMode
	18, // 15: ironflow.v1.GetFunctionExecutionRoutingResponse.transition_started_at:type_name -> google.protobuf.Timestamp
	18, // 16: ironflow.v1.GetFunctionExecutionRoutingResponse.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 17: ironflow.v1.DeploymentService.RegisterDeployment:input_type -> ironflow.v1.RegisterDeploymentRequest
	5,  // 18: ironflow.v1.DeploymentService.GetDeployment:input_type -> ironflow.v1.GetDeploymentRequest
	7,  // 19: ironflow.v1.DeploymentService.ListDeployments:input_type -> ironflow.v1.ListDeploymentsRequest
	9,  // 20: ironflow.v1.DeploymentService.GetFunctionExecutionRouting:input_type -> ironflow.v1.GetFunctionExecutionRoutingRequest
	4,  // 21: ironflow.v1.DeploymentService.RegisterDeployment:output_type -> ironflow.v1.RegisterDeploymentResponse
	6,  // 22: ironflow.v1.DeploymentService.GetDeployment:output_type -> ironflow.v1.GetDeploymentResponse
	8,  // 23: ironflow.v1.DeploymentService.ListDeployments:output_type -> ironflow.v1.ListDeploymentsResponse
	10, // 24: ironflow.v1.DeploymentService.GetFunctionExecutionRouting:output_type -> ironflow.v1.GetFunctionExecutionRoutingResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_ironflow_v1_deployment_proto_init() }
func file_ironflow_v1_deployment_proto_init() {
	if File_ironflow_v1_deployment_proto != nil {
		return
	}
	file_ironflow_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironflow_v1_deployment_proto_rawDesc), len(file_ironflow_v1_deployment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironflow_v1_deployment_proto_goTypes,
		DependencyIndexes: file_ironflow_v1_deployment_proto_depIdxs,
		EnumInfos:         file_ironflow_v1_deployment_proto_enumTypes,
		MessageInfos:      file_ironflow_v1_deployment_proto_msgTypes,
	}.Build()
	File_ironflow_v1_deployment_proto = out.File
	file_ironflow_v1_deployment_proto_goTypes = nil
	file_ironflow_v1_deployment_proto_depIdxs = nil
}
