// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironflow/v1/entity_stream.proto

package ironflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEventRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EntityId   string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EventName  string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Data       *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Set ONLY when the payload is not a JSON object, which data cannot
	// represent (#1963). Readers take this when present and fall back to
	// data, so an object costs no extra bytes and old clients are
	// unaffected.
	DataValue       *structpb.Value  `protobuf:"bytes,9,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
	ExpectedVersion int64            `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // -1 = skip check, 0 = new stream
	IdempotencyKey  string           `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Version         int32            `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`  // Event schema version
	Metadata        *structpb.Struct `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"` // Cross-cutting metadata (causation, correlation, tenant, trace)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendEventRequest) Reset() {
	*x = AppendEventRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventRequest) ProtoMessage() {}

func (x *AppendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventRequest.ProtoReflect.Descriptor instead.
func (*AppendEventRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEventRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AppendEventRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AppendEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *AppendEventRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppendEventRequest) GetDataValue() *structpb.Value {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *AppendEventRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *AppendEventRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AppendEventRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppendEventRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AppendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityVersion int64                  `protobuf:"varint,1,opt,name=entity_version,json=entityVersion,proto3" json:"entity_version,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Always 0 under the transactional outbox (#487). The NATS sequence is
	// not known at AppendEvent time because publishing is deferred to a
	// per-node outbox worker. For read-your-writes, call WaitForEvent(event_id),
	// which blocks until the outbox drains the row and returns the resolved seq
	// in WaitProjectionCatchupResponse.target_seq. Prior to #487 this field
	// carried the NATS seq inline; callers that still read it must migrate.
	Sequence      uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventResponse) Reset() {
	*x = AppendEventResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventResponse) ProtoMessage() {}

func (x *AppendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventResponse.ProtoReflect.Descriptor instead.
func (*AppendEventResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEventResponse) GetEntityVersion() int64 {
	if x != nil {
		return x.EntityVersion
	}
	return 0
}

func (x *AppendEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AppendEventResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ReadStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FromVersion   int64                  `protobuf:"varint,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"` // "forward" (default) or "backward"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamRequest) Reset() {
	*x = ReadStreamRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamRequest) ProtoMessage() {}

func (x *ReadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamRequest.ProtoReflect.Descriptor instead.
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ReadStreamRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ReadStreamRequest) GetFromVersion() int64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

func (x *ReadStreamRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadStreamRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type ReadStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StreamEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamResponse) Reset() {
	*x = ReadStreamResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamResponse) ProtoMessage() {}

func (x *ReadStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamResponse.ProtoReflect.Descriptor instead.
func (*ReadStreamResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{3}
}

func (x *ReadStreamResponse) GetEvents() []*StreamEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReadStreamResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data  *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Set ONLY when the payload is not a JSON object, which data cannot
	// represent (#1963). Readers take this when present and fall back to
	// data, so an object costs no extra bytes and old clients are
	// unaffected.
	DataValue     *structpb.Value        `protobuf:"bytes,9,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
	EntityVersion int64                  `protobuf:"varint,4,opt,name=entity_version,json=entityVersion,proto3" json:"entity_version,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StreamEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamEvent) GetDataValue() *structpb.Value {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *StreamEvent) GetEntityVersion() int64 {
	if x != nil {
		return x.EntityVersion
	}
	return 0
}

func (x *StreamEvent) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StreamEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StreamEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetStreamInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamInfoRequest) Reset() {
	*x = GetStreamInfoRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoRequest) ProtoMessage() {}

func (x *GetStreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{5}
}

func (x *GetStreamInfoRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetStreamInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	EventCount    int64                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamInfoResponse) Reset() {
	*x = GetStreamInfoResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoResponse) ProtoMessage() {}

func (x *GetStreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{6}
}

func (x *GetStreamInfoResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetStreamInfoResponse) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *GetStreamInfoResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetStreamInfoResponse) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *GetStreamInfoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetStreamInfoResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // optional filter
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ListStreamsRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListStreamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListStreamsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Streams       []*GetStreamInfoResponse `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	TotalCount    int32                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{8}
}

func (x *ListStreamsResponse) GetStreams() []*GetStreamInfoResponse {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *ListStreamsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetEntityHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FromVersion   int64                  `protobuf:"varint,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"` // cursor: start from this entity_version (inclusive), 0 = beginning
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                // max events per page, default 50
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`                         // "forward" (oldest first) or "backward" (newest first), default "forward"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityHistoryRequest) Reset() {
	*x = GetEntityHistoryRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityHistoryRequest) ProtoMessage() {}

func (x *GetEntityHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetEntityHistoryRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{9}
}

func (x *GetEntityHistoryRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetEntityHistoryRequest) GetFromVersion() int64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

func (x *GetEntityHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetEntityHistoryRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type GetEntityHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EntityHistoryEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`    // next entity_version to fetch, 0 = no more pages
	TotalEvents   int64                  `protobuf:"varint,3,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"` // total entity events count
	Info          *EntityHistoryInfo     `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`                                   // entity metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityHistoryResponse) Reset() {
	*x = GetEntityHistoryResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityHistoryResponse) ProtoMessage() {}

func (x *GetEntityHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetEntityHistoryResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{10}
}

func (x *GetEntityHistoryResponse) GetEntries() []*EntityHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetEntityHistoryResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetEntityHistoryResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetEntityHistoryResponse) GetInfo() *EntityHistoryInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type EntityHistoryInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntityId        string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType      string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	CurrentVersion  int64                  `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	TotalEventCount int64                  `protobuf:"varint,4,opt,name=total_event_count,json=totalEventCount,proto3" json:"total_event_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EntityHistoryInfo) Reset() {
	*x = EntityHistoryInfo{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityHistoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityHistoryInfo) ProtoMessage() {}

func (x *EntityHistoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityHistoryInfo.ProtoReflect.Descriptor instead.
func (*EntityHistoryInfo) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{11}
}

func (x *EntityHistoryInfo) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityHistoryInfo) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityHistoryInfo) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *EntityHistoryInfo) GetTotalEventCount() int64 {
	if x != nil {
		return x.TotalEventCount
	}
	return 0
}

func (x *EntityHistoryInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EntityHistoryInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EntityHistoryEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventData *structpb.Struct       `protobuf:"bytes,3,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	// Set ONLY when the payload is not a JSON object, which event_data cannot
	// represent (#1963). Readers take this when present and fall back to
	// event_data, so an object costs no extra bytes and old clients are
	// unaffected.
	EventDataValue *structpb.Value        `protobuf:"bytes,9,opt,name=event_data_value,json=eventDataValue,proto3" json:"event_data_value,omitempty"`
	EntityVersion  int64                  `protobuf:"varint,4,opt,name=entity_version,json=entityVersion,proto3" json:"entity_version,omitempty"`
	SchemaVersion  int32                  `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Runs           []*EntityHistoryRun    `protobuf:"bytes,8,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityHistoryEntry) Reset() {
	*x = EntityHistoryEntry{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityHistoryEntry) ProtoMessage() {}

func (x *EntityHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityHistoryEntry.ProtoReflect.Descriptor instead.
func (*EntityHistoryEntry) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{12}
}

func (x *EntityHistoryEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EntityHistoryEntry) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EntityHistoryEntry) GetEventData() *structpb.Struct {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *EntityHistoryEntry) GetEventDataValue() *structpb.Value {
	if x != nil {
		return x.EventDataValue
	}
	return nil
}

func (x *EntityHistoryEntry) GetEntityVersion() int64 {
	if x != nil {
		return x.EntityVersion
	}
	return 0
}

func (x *EntityHistoryEntry) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EntityHistoryEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EntityHistoryEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EntityHistoryEntry) GetRuns() []*EntityHistoryRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

type EntityHistoryRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FunctionId    string                 `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Steps         []*EntityHistoryStep   `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityHistoryRun) Reset() {
	*x = EntityHistoryRun{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityHistoryRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityHistoryRun) ProtoMessage() {}

func (x *EntityHistoryRun) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityHistoryRun.ProtoReflect.Descriptor instead.
func (*EntityHistoryRun) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{13}
}

func (x *EntityHistoryRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EntityHistoryRun) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *EntityHistoryRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EntityHistoryRun) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *EntityHistoryRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *EntityHistoryRun) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *EntityHistoryRun) GetSteps() []*EntityHistoryStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type EntityHistoryStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StepType      string                 `protobuf:"bytes,3,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityHistoryStep) Reset() {
	*x = EntityHistoryStep{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityHistoryStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityHistoryStep) ProtoMessage() {}

func (x *EntityHistoryStep) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityHistoryStep.ProtoReflect.Descriptor instead.
func (*EntityHistoryStep) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{14}
}

func (x *EntityHistoryStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *EntityHistoryStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityHistoryStep) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *EntityHistoryStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EntityHistoryStep) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *EntityHistoryStep) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityVersion int64                  `protobuf:"varint,3,opt,name=entity_version,json=entityVersion,proto3" json:"entity_version,omitempty"` // The stream version this snapshot represents
	State         *structpb.Struct       `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                       // Materialized state at this version
	// Set ONLY when the payload is not a JSON object, which state cannot
	// represent (#1963). Readers take this when present and fall back to
	// state, so an object costs no extra bytes and old clients are
	// unaffected.
	StateValue    *structpb.Value `protobuf:"bytes,5,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSnapshotRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CreateSnapshotRequest) GetEntityVersion() int64 {
	if x != nil {
		return x.EntityVersion
	}
	return 0
}

func (x *CreateSnapshotRequest) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CreateSnapshotRequest) GetStateValue() *structpb.Value {
	if x != nil {
		return x.StateValue
	}
	return nil
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	BeforeVersion int64                  `protobuf:"varint,2,opt,name=before_version,json=beforeVersion,proto3" json:"before_version,omitempty"` // Return latest snapshot at or before this version; 0 = latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{17}
}

func (x *GetSnapshotRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetSnapshotRequest) GetBeforeVersion() int64 {
	if x != nil {
		return x.BeforeVersion
	}
	return 0
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityVersion int64                  `protobuf:"varint,4,opt,name=entity_version,json=entityVersion,proto3" json:"entity_version,omitempty"`
	State         *structpb.Struct       `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// Set ONLY when the payload is not a JSON object, which state cannot
	// represent (#1963). Readers take this when present and fall back to
	// state, so an object costs no extra bytes and old clients are
	// unaffected.
	StateValue    *structpb.Value        `protobuf:"bytes,7,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_entity_stream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_entity_stream_proto_rawDescGZIP(), []int{18}
}

func (x *GetSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *GetSnapshotResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetSnapshotResponse) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *GetSnapshotResponse) GetEntityVersion() int64 {
	if x != nil {
		return x.EntityVersion
	}
	return 0
}

func (x *GetSnapshotResponse) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetSnapshotResponse) GetStateValue() *structpb.Value {
	if x != nil {
		return x.StateValue
	}
	return nil
}

func (x *GetSnapshotResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_ironflow_v1_entity_stream_proto protoreflect.FileDescriptor

const file_ironflow_v1_entity_stream_proto_rawDesc = "" +
	"\n" +
	"\x1fironflow/v1/entity_stream.proto\x12\vironflow.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x02\n" +
	"\x12AppendEventRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x125\n" +
	"\n" +
	"data_value\x18\t \x01(\v2\x16.google.protobuf.ValueR\tdataValue\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"s\n" +
	"\x13AppendEventResponse\x12%\n" +
	"\x0eentity_version\x18\x01 \x01(\x03R\rentityVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\x87\x01\n" +
	"\x11ReadStreamRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\x03R\vfromVersion\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\"g\n" +
	"\x12ReadStreamResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.ironflow.v1.StreamEventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xdd\x02\n" +
	"\vStreamEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x125\n" +
	"\n" +
	"data_value\x18\t \x01(\v2\x16.google.protobuf.ValueR\tdataValue\x12%\n" +
	"\x0eentity_version\x18\x04 \x01(\x03R\rentityVersion\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"3\n" +
	"\x14GetStreamInfoRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"\x86\x02\n" +
	"\x15GetStreamInfoResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x03R\n" +
	"eventCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"c\n" +
	"\x12ListStreamsRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"t\n" +
	"\x13ListStreamsResponse\x12<\n" +
	"\astreams\x18\x01 \x03(\v2\".ironflow.v1.GetStreamInfoResponseR\astreams\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x8d\x01\n" +
	"\x17GetEntityHistoryRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\x03R\vfromVersion\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\"\xcd\x01\n" +
	"\x18GetEntityHistoryResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.ironflow.v1.EntityHistoryEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12!\n" +
	"\ftotal_events\x18\x03 \x01(\x03R\vtotalEvents\x122\n" +
	"\x04info\x18\x04 \x01(\v2\x1e.ironflow.v1.EntityHistoryInfoR\x04info\"\x9c\x02\n" +
	"\x11EntityHistoryInfo\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\x03R\x0ecurrentVersion\x12*\n" +
	"\x11total_event_count\x18\x04 \x01(\x03R\x0ftotalEventCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x03\n" +
	"\x12EntityHistoryEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x126\n" +
	"\n" +
	"event_data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\teventData\x12@\n" +
	"\x10event_data_value\x18\t \x01(\v2\x16.google.protobuf.ValueR\x0eeventDataValue\x12%\n" +
	"\x0eentity_version\x18\x04 \x01(\x03R\rentityVersion\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\x04runs\x18\b \x03(\v2\x1d.ironflow.v1.EntityHistoryRunR\x04runs\"\xab\x02\n" +
	"\x10EntityHistoryRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\tR\n" +
	"functionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x124\n" +
	"\x05steps\x18\a \x03(\v2\x1e.ironflow.v1.EntityHistoryStepR\x05steps\"\xbb\x01\n" +
	"\x11EntityHistoryStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tstep_type\x18\x03 \x01(\tR\bstepType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xe4\x01\n" +
	"\x15CreateSnapshotRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12%\n" +
	"\x0eentity_version\x18\x03 \x01(\x03R\rentityVersion\x12-\n" +
	"\x05state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05state\x127\n" +
	"\vstate_value\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"stateValue\"9\n" +
	"\x16CreateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"X\n" +
	"\x12GetSnapshotRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12%\n" +
	"\x0ebefore_version\x18\x02 \x01(\x03R\rbeforeVersion\"\xbe\x02\n" +
	"\x13GetSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12%\n" +
	"\x0eentity_version\x18\x04 \x01(\x03R\rentityVersion\x12-\n" +
	"\x05state\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05state\x127\n" +
	"\vstate_value\x18\a \x01(\v2\x16.google.protobuf.ValueR\n" +
	"stateValue\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x87\x05\n" +
	"\x13EntityStreamService\x12P\n" +
	"\vAppendEvent\x12\x1f.ironflow.v1.AppendEventRequest\x1a .ironflow.v1.AppendEventResponse\x12R\n" +
	"\n" +
	"ReadStream\x12\x1e.ironflow.v1.ReadStreamRequest\x1a\x1f.ironflow.v1.ReadStreamResponse\"\x03\x90\x02\x01\x12[\n" +
	"\rGetStreamInfo\x12!.ironflow.v1.GetStreamInfoRequest\x1a\".ironflow.v1.GetStreamInfoResponse\"\x03\x90\x02\x01\x12U\n" +
	"\vListStreams\x12\x1f.ironflow.v1.ListStreamsRequest\x1a .ironflow.v1.ListStreamsResponse\"\x03\x90\x02\x01\x12d\n" +
	"\x10GetEntityHistory\x12$.ironflow.v1.GetEntityHistoryRequest\x1a%.ironflow.v1.GetEntityHistoryResponse\"\x03\x90\x02\x01\x12Y\n" +
	"\x0eCreateSnapshot\x12\".ironflow.v1.CreateSnapshotRequest\x1a#.ironflow.v1.CreateSnapshotResponse\x12U\n" +
	"\vGetSnapshot\x12\x1f.ironflow.v1.GetSnapshotRequest\x1a .ironflow.v1.GetSnapshotResponse\"\x03\x90\x02\x01B:Z8github.com/sahina/ironflow-go/api/ironflow/v1;ironflowv1b\x06proto3"

var (
	file_ironflow_v1_entity_stream_proto_rawDescOnce sync.Once
	file_ironflow_v1_entity_stream_proto_rawDescData []byte
)

func file_ironflow_v1_entity_stream_proto_rawDescGZIP() []byte {
	file_ironflow_v1_entity_stream_proto_rawDescOnce.Do(func() {
		file_ironflow_v1_entity_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironflow_v1_entity_stream_proto_rawDesc), len(file_ironflow_v1_entity_stream_proto_rawDesc)))
	})
	return file_ironflow_v1_entity_stream_proto_rawDescData
}

var file_ironflow_v1_entity_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ironflow_v1_entity_stream_proto_goTypes = []any{
	(*AppendEventRequest)(nil),       // 0: ironflow.v1.AppendEventRequest
	(*AppendEventResponse)(nil),      // 1: ironflow.v1.AppendEventResponse
	(*ReadStreamRequest)(nil),        // 2: ironflow.v1.ReadStreamRequest
	(*ReadStreamResponse)(nil),       // 3: ironflow.v1.ReadStreamResponse
	(*StreamEvent)(nil),              // 4: ironflow.v1.StreamEvent
	(*GetStreamInfoRequest)(nil),     // 5: ironflow.v1.GetStreamInfoRequest
	(*GetStreamInfoResponse)(nil),    // 6: ironflow.v1.GetStreamInfoResponse
	(*ListStreamsRequest)(nil),       // 7: ironflow.v1.ListStreamsRequest
	(*ListStreamsResponse)(nil),      // 8: ironflow.v1.ListStreamsResponse
	(*GetEntityHistoryRequest)(nil),  // 9: ironflow.v1.GetEntityHistoryRequest
	(*GetEntityHistoryResponse)(nil), // 10: ironflow.v1.GetEntityHistoryResponse
	(*EntityHistoryInfo)(nil),        // 11: ironflow.v1.EntityHistoryInfo
	(*EntityHistoryEntry)(nil),       // 12: ironflow.v1.EntityHistoryEntry
	(*EntityHistoryRun)(nil),         // 13: ironflow.v1.EntityHistoryRun
	(*EntityHistoryStep)(nil),        // 14: ironflow.v1.EntityHistoryStep
	(*CreateSnapshotRequest)(nil),    // 15: ironflow.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),   // 16: ironflow.v1.CreateSnapshotResponse
	(*GetSnapshotRequest)(nil),       // 17: ironflow.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),      // 18: ironflow.v1.GetSnapshotResponse
	(*structpb.Struct)(nil),          // 19: google.protobuf.Struct
	(*structpb.Value)(nil),           // 20: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_ironflow_v1_entity_stream_proto_depIdxs = []int32{
	19, // 0: ironflow.v1.AppendEventRequest.data:type_name -> google.protobuf.Struct
	20, // 1: ironflow.v1.AppendEventRequest.data_value:type_name -> google.protobuf.Value
	19, // 2: ironflow.v1.AppendEventRequest.metadata:type_name -> google.protobuf.Struct
	4,  // 3: ironflow.v1.ReadStreamResponse.events:type_name -> ironflow.v1.StreamEvent
	19, // 4: ironflow.v1.StreamEvent.data:type_name -> google.protobuf.Struct
	20, // 5: ironflow.v1.StreamEvent.data_value:type_name -> google.protobuf.Value
	21, // 6: ironflow.v1.StreamEvent.timestamp:type_name -> google.protobuf.Timestamp
	19, // 7: ironflow.v1.StreamEvent.metadata:type_name -> google.protobuf.Struct
	21, // 8: ironflow.v1.GetStreamInfoResponse.created_at:type_name -> google.protobuf.Timestamp
	21, // 9: ironflow.v1.GetStreamInfoResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 10: ironflow.v1.ListStreamsResponse.streams:type_name -> ironflow.v1.GetStreamInfoResponse
	12, // 11: ironflow.v1.GetEntityHistoryResponse.entries:type_name -> ironflow.v1.EntityHistoryEntry
	11, // 12: ironflow.v1.GetEntityHistoryResponse.info:type_name -> ironflow.v1.EntityHistoryInfo
	21, // 13: ironflow.v1.EntityHistoryInfo.created_at:type_name -> google.protobuf.Timestamp
	21, // 14: ironflow.v1.EntityHistoryInfo.updated_at:type_name -> google.protobuf.Timestamp
	19, // 15: ironflow.v1.EntityHistoryEntry.event_data:type_name -> google.protobuf.Struct
	20, // 16: ironflow.v1.EntityHistoryEntry.event_data_value:type_name -> google.protobuf.Value
	21, // 17: ironflow.v1.EntityHistoryEntry.timestamp:type_name -> google.protobuf.Timestamp
	13, // 18: ironflow.v1.EntityHistoryEntry.runs:type_name -> ironflow.v1.EntityHistoryRun
	21, // 19: ironflow.v1.EntityHistoryRun.started_at:type_name -> google.protobuf.Timestamp
	21, // 20: ironflow.v1.EntityHistoryRun.ended_at:type_name -> google.protobuf.Timestamp
	14, // 21: ironflow.v1.EntityHistoryRun.steps:type_name -> ironflow.v1.EntityHistoryStep
	19, // 22: ironflow.v1.CreateSnapshotRequest.state:type_name -> google.protobuf.Struct
	20, // 23: ironflow.v1.CreateSnapshotRequest.state_value:type_name -> google.protobuf.Value
	19, // 24: ironflow.v1.GetSnapshotResponse.state:type_name -> google.protobuf.Struct
	20, // 25: ironflow.v1.GetSnapshotResponse.state_value:type_name -> google.protobuf.Value
	21, // 26: ironflow.v1.GetSnapshotResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 27: ironflow.v1.EntityStreamService.AppendEvent:input_type -> ironflow.v1.AppendEventRequest
	2,  // 28: ironflow.v1.EntityStreamService.ReadStream:input_type -> ironflow.v1.ReadStreamRequest
	5,  // 29: ironflow.v1.EntityStreamService.GetStreamInfo:input_type -> ironflow.v1.GetStreamInfoRequest
	7,  // 30: ironflow.v1.EntityStreamService.ListStreams:input_type -> ironflow.v1.ListStreamsRequest
	9,  // 31: ironflow.v1.EntityStreamService.GetEntityHistory:input_type -> ironflow.v1.GetEntityHistoryRequest
	15, // 32: ironflow.v1.EntityStreamService.CreateSnapshot:input_type -> ironflow.v1.CreateSnapshotRequest
	17, // 33: ironflow.v1.EntityStreamService.GetSnapshot:input_type -> ironflow.v1.GetSnapshotRequest
	1,  // 34: ironflow.v1.EntityStreamService.AppendEvent:output_type -> ironflow.v1.AppendEventResponse
	3,  // 35: ironflow.v1.EntityStreamService.ReadStream:output_type -> ironflow.v1.ReadStreamResponse
	6,  // 36: ironflow.v1.EntityStreamService.GetStreamInfo:output_type -> ironflow.v1.GetStreamInfoResponse
	8,  // 37: ironflow.v1.EntityStreamService.ListStreams:output_type -> ironflow.v1.ListStreamsResponse
	10, // 38: ironflow.v1.EntityStreamService.GetEntityHistory:output_type -> ironflow.v1.GetEntityHistoryResponse
	16, // 39: ironflow.v1.EntityStreamService.CreateSnapshot:output_type -> ironflow.v1.CreateSnapshotResponse
	18, // 40: ironflow.v1.EntityStreamService.GetSnapshot:output_type -> ironflow.v1.GetSnapshotResponse
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_ironflow_v1_entity_stream_proto_init() }
func file_ironflow_v1_entity_stream_proto_init() {
	if File_ironflow_v1_entity_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironflow_v1_entity_stream_proto_rawDesc), len(file_ironflow_v1_entity_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironflow_v1_entity_stream_proto_goTypes,
		DependencyIndexes: file_ironflow_v1_entity_stream_proto_depIdxs,
		MessageInfos:      file_ironflow_v1_entity_stream_proto_msgTypes,
	}.Build()
	File_ironflow_v1_entity_stream_proto = out.File
	file_ironflow_v1_entity_stream_proto_goTypes = nil
	file_ironflow_v1_entity_stream_proto_depIdxs = nil
}
