// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironflow/v1/environment.proto

package ironflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvironmentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Environment ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// API key for this environment
	ApiKey string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentInfo) Reset() {
	*x = EnvironmentInfo{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentInfo) ProtoMessage() {}

func (x *EnvironmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentInfo.ProtoReflect.Descriptor instead.
func (*EnvironmentInfo) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{0}
}

func (x *EnvironmentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvironmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentInfo) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *EnvironmentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnvironmentInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for the environment
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentRequest) Reset() {
	*x = CreateEnvironmentRequest{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentRequest) ProtoMessage() {}

func (x *CreateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Environment ID
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEnvironmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvironmentsRequest) Reset() {
	*x = ListEnvironmentsRequest{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvironmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvironmentsRequest) ProtoMessage() {}

func (x *ListEnvironmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvironmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnvironmentsRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{3}
}

type ListEnvironmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All environments
	Environments  []*EnvironmentInfo `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvironmentsResponse) Reset() {
	*x = ListEnvironmentsResponse{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvironmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvironmentsResponse) ProtoMessage() {}

func (x *ListEnvironmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvironmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnvironmentsResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{4}
}

func (x *ListEnvironmentsResponse) GetEnvironments() []*EnvironmentInfo {
	if x != nil {
		return x.Environments
	}
	return nil
}

type DeleteEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Environment ID
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentRequest) Reset() {
	*x = DeleteEnvironmentRequest{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentRequest) ProtoMessage() {}

func (x *DeleteEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEnvironmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentResponse) Reset() {
	*x = DeleteEnvironmentResponse{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentResponse) ProtoMessage() {}

func (x *DeleteEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEnvironmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RotateAPIKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Environment ID
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAPIKeyRequest) Reset() {
	*x = RotateAPIKeyRequest{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAPIKeyRequest) ProtoMessage() {}

func (x *RotateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{7}
}

func (x *RotateAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RotateAPIKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Environment ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Environment name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Newly generated API key
	ApiKey        string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAPIKeyResponse) Reset() {
	*x = RotateAPIKeyResponse{}
	mi := &file_ironflow_v1_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAPIKeyResponse) ProtoMessage() {}

func (x *RotateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_environment_proto_rawDescGZIP(), []int{8}
}

func (x *RotateAPIKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RotateAPIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RotateAPIKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_ironflow_v1_environment_proto protoreflect.FileDescriptor

const file_ironflow_v1_environment_proto_rawDesc = "" +
	"\n" +
	"\x1dironflow/v1/environment.proto\x12\vironflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x01\n" +
	"\x0fEnvironmentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\".\n" +
	"\x18CreateEnvironmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x15GetEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17ListEnvironmentsRequest\"\\\n" +
	"\x18ListEnvironmentsResponse\x12@\n" +
	"\fenvironments\x18\x01 \x03(\v2\x1c.ironflow.v1.EnvironmentInfoR\fenvironments\"*\n" +
	"\x18DeleteEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteEnvironmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x13RotateAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x14RotateAPIKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey2\xdc\x03\n" +
	"\x12EnvironmentService\x12X\n" +
	"\x11CreateEnvironment\x12%.ironflow.v1.CreateEnvironmentRequest\x1a\x1c.ironflow.v1.EnvironmentInfo\x12R\n" +
	"\x0eGetEnvironment\x12\".ironflow.v1.GetEnvironmentRequest\x1a\x1c.ironflow.v1.EnvironmentInfo\x12_\n" +
	"\x10ListEnvironments\x12$.ironflow.v1.ListEnvironmentsRequest\x1a%.ironflow.v1.ListEnvironmentsResponse\x12b\n" +
	"\x11DeleteEnvironment\x12%.ironflow.v1.DeleteEnvironmentRequest\x1a&.ironflow.v1.DeleteEnvironmentResponse\x12S\n" +
	"\fRotateAPIKey\x12 .ironflow.v1.RotateAPIKeyRequest\x1a!.ironflow.v1.RotateAPIKeyResponseB:Z8github.com/sahina/ironflow-go/api/ironflow/v1;ironflowv1b\x06proto3"

var (
	file_ironflow_v1_environment_proto_rawDescOnce sync.Once
	file_ironflow_v1_environment_proto_rawDescData []byte
)

func file_ironflow_v1_environment_proto_rawDescGZIP() []byte {
	file_ironflow_v1_environment_proto_rawDescOnce.Do(func() {
		file_ironflow_v1_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironflow_v1_environment_proto_rawDesc), len(file_ironflow_v1_environment_proto_rawDesc)))
	})
	return file_ironflow_v1_environment_proto_rawDescData
}

var file_ironflow_v1_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ironflow_v1_environment_proto_goTypes = []any{
	(*EnvironmentInfo)(nil),           // 0: ironflow.v1.EnvironmentInfo
	(*CreateEnvironmentRequest)(nil),  // 1: ironflow.v1.CreateEnvironmentRequest
	(*GetEnvironmentRequest)(nil),     // 2: ironflow.v1.GetEnvironmentRequest
	(*ListEnvironmentsRequest)(nil),   // 3: ironflow.v1.ListEnvironmentsRequest
	(*ListEnvironmentsResponse)(nil),  // 4: ironflow.v1.ListEnvironmentsResponse
	(*DeleteEnvironmentRequest)(nil),  // 5: ironflow.v1.DeleteEnvironmentRequest
	(*DeleteEnvironmentResponse)(nil), // 6: ironflow.v1.DeleteEnvironmentResponse
	(*RotateAPIKeyRequest)(nil),       // 7: ironflow.v1.RotateAPIKeyRequest
	(*RotateAPIKeyResponse)(nil),      // 8: ironflow.v1.RotateAPIKeyResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_ironflow_v1_environment_proto_depIdxs = []int32{
	9, // 0: ironflow.v1.EnvironmentInfo.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: ironflow.v1.EnvironmentInfo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: ironflow.v1.ListEnvironmentsResponse.environments:type_name -> ironflow.v1.EnvironmentInfo
	1, // 3: ironflow.v1.EnvironmentService.CreateEnvironment:input_type -> ironflow.v1.CreateEnvironmentRequest
	2, // 4: ironflow.v1.EnvironmentService.GetEnvironment:input_type -> ironflow.v1.GetEnvironmentRequest
	3, // 5: ironflow.v1.EnvironmentService.ListEnvironments:input_type -> ironflow.v1.ListEnvironmentsRequest
	5, // 6: ironflow.v1.EnvironmentService.DeleteEnvironment:input_type -> ironflow.v1.DeleteEnvironmentRequest
	7, // 7: ironflow.v1.EnvironmentService.RotateAPIKey:input_type -> ironflow.v1.RotateAPIKeyRequest
	0, // 8: ironflow.v1.EnvironmentService.CreateEnvironment:output_type -> ironflow.v1.EnvironmentInfo
	0, // 9: ironflow.v1.EnvironmentService.GetEnvironment:output_type -> ironflow.v1.EnvironmentInfo
	4, // 10: ironflow.v1.EnvironmentService.ListEnvironments:output_type -> ironflow.v1.ListEnvironmentsResponse
	6, // 11: ironflow.v1.EnvironmentService.DeleteEnvironment:output_type -> ironflow.v1.DeleteEnvironmentResponse
	8, // 12: ironflow.v1.EnvironmentService.RotateAPIKey:output_type -> ironflow.v1.RotateAPIKeyResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ironflow_v1_environment_proto_init() }
func file_ironflow_v1_environment_proto_init() {
	if File_ironflow_v1_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironflow_v1_environment_proto_rawDesc), len(file_ironflow_v1_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironflow_v1_environment_proto_goTypes,
		DependencyIndexes: file_ironflow_v1_environment_proto_depIdxs,
		MessageInfos:      file_ironflow_v1_environment_proto_msgTypes,
	}.Build()
	File_ironflow_v1_environment_proto = out.File
	file_ironflow_v1_environment_proto_goTypes = nil
	file_ironflow_v1_environment_proto_depIdxs = nil
}
