// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironflow/v1/types.proto

package ironflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionStatus int32

const (
	FunctionStatus_FUNCTION_STATUS_UNSPECIFIED FunctionStatus = 0
	FunctionStatus_FUNCTION_STATUS_ACTIVE      FunctionStatus = 1
	FunctionStatus_FUNCTION_STATUS_PAUSED      FunctionStatus = 2
	FunctionStatus_FUNCTION_STATUS_ARCHIVED    FunctionStatus = 3
)

// Enum value maps for FunctionStatus.
var (
	FunctionStatus_name = map[int32]string{
		0: "FUNCTION_STATUS_UNSPECIFIED",
		1: "FUNCTION_STATUS_ACTIVE",
		2: "FUNCTION_STATUS_PAUSED",
		3: "FUNCTION_STATUS_ARCHIVED",
	}
	FunctionStatus_value = map[string]int32{
		"FUNCTION_STATUS_UNSPECIFIED": 0,
		"FUNCTION_STATUS_ACTIVE":      1,
		"FUNCTION_STATUS_PAUSED":      2,
		"FUNCTION_STATUS_ARCHIVED":    3,
	}
)

func (x FunctionStatus) Enum() *FunctionStatus {
	p := new(FunctionStatus)
	*p = x
	return p
}

func (x FunctionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_types_proto_enumTypes[0].Descriptor()
}

func (FunctionStatus) Type() protoreflect.EnumType {
	return &file_ironflow_v1_types_proto_enumTypes[0]
}

func (x FunctionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionStatus.Descriptor instead.
func (FunctionStatus) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{0}
}

type ExecutionMode int32

const (
	ExecutionMode_EXECUTION_MODE_UNSPECIFIED ExecutionMode = 0
	ExecutionMode_EXECUTION_MODE_PUSH        ExecutionMode = 1
	ExecutionMode_EXECUTION_MODE_PULL        ExecutionMode = 2
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "EXECUTION_MODE_UNSPECIFIED",
		1: "EXECUTION_MODE_PUSH",
		2: "EXECUTION_MODE_PULL",
	}
	ExecutionMode_value = map[string]int32{
		"EXECUTION_MODE_UNSPECIFIED": 0,
		"EXECUTION_MODE_PUSH":        1,
		"EXECUTION_MODE_PULL":        2,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_types_proto_enumTypes[1].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_ironflow_v1_types_proto_enumTypes[1]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{1}
}

type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED RunStatus = 0
	RunStatus_RUN_STATUS_RUNNING     RunStatus = 2
	RunStatus_RUN_STATUS_COMPLETED   RunStatus = 3
	RunStatus_RUN_STATUS_FAILED      RunStatus = 4
	RunStatus_RUN_STATUS_CANCELLED   RunStatus = 5
	RunStatus_RUN_STATUS_PAUSED      RunStatus = 6
	// A runnable execution segment exists in dispatch_queue; capacity admission
	// is pending. #1206 / ADR 0037.
	RunStatus_RUN_STATUS_WAITING_FOR_CAPACITY RunStatus = 7
	// Not runnable: blocked on a durable wait (sleep, event, invoke, retry_delay,
	// recovery_grace). #1206 / ADR 0037.
	RunStatus_RUN_STATUS_WAITING RunStatus = 8
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		2: "RUN_STATUS_RUNNING",
		3: "RUN_STATUS_COMPLETED",
		4: "RUN_STATUS_FAILED",
		5: "RUN_STATUS_CANCELLED",
		6: "RUN_STATUS_PAUSED",
		7: "RUN_STATUS_WAITING_FOR_CAPACITY",
		8: "RUN_STATUS_WAITING",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED":          0,
		"RUN_STATUS_RUNNING":              2,
		"RUN_STATUS_COMPLETED":            3,
		"RUN_STATUS_FAILED":               4,
		"RUN_STATUS_CANCELLED":            5,
		"RUN_STATUS_PAUSED":               6,
		"RUN_STATUS_WAITING_FOR_CAPACITY": 7,
		"RUN_STATUS_WAITING":              8,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_types_proto_enumTypes[2].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_ironflow_v1_types_proto_enumTypes[2]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{2}
}

type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED StepStatus = 0
	StepStatus_STEP_STATUS_PENDING     StepStatus = 1
	StepStatus_STEP_STATUS_RUNNING     StepStatus = 2
	StepStatus_STEP_STATUS_COMPLETED   StepStatus = 3
	StepStatus_STEP_STATUS_FAILED      StepStatus = 4
	StepStatus_STEP_STATUS_SLEEPING    StepStatus = 5
	StepStatus_STEP_STATUS_WAITING     StepStatus = 6
	StepStatus_STEP_STATUS_TIMED_OUT   StepStatus = 7
	StepStatus_STEP_STATUS_RETRYING    StepStatus = 8
	StepStatus_STEP_STATUS_DEAD        StepStatus = 9
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_PENDING",
		2: "STEP_STATUS_RUNNING",
		3: "STEP_STATUS_COMPLETED",
		4: "STEP_STATUS_FAILED",
		5: "STEP_STATUS_SLEEPING",
		6: "STEP_STATUS_WAITING",
		7: "STEP_STATUS_TIMED_OUT",
		8: "STEP_STATUS_RETRYING",
		9: "STEP_STATUS_DEAD",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED": 0,
		"STEP_STATUS_PENDING":     1,
		"STEP_STATUS_RUNNING":     2,
		"STEP_STATUS_COMPLETED":   3,
		"STEP_STATUS_FAILED":      4,
		"STEP_STATUS_SLEEPING":    5,
		"STEP_STATUS_WAITING":     6,
		"STEP_STATUS_TIMED_OUT":   7,
		"STEP_STATUS_RETRYING":    8,
		"STEP_STATUS_DEAD":        9,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_types_proto_enumTypes[3].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_ironflow_v1_types_proto_enumTypes[3]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{3}
}

type StepType int32

const (
	StepType_STEP_TYPE_UNSPECIFIED     StepType = 0
	StepType_STEP_TYPE_INVOKE          StepType = 1
	StepType_STEP_TYPE_SLEEP           StepType = 2
	StepType_STEP_TYPE_WAIT_FOR_EVENT  StepType = 3
	StepType_STEP_TYPE_COMPENSATE      StepType = 4
	StepType_STEP_TYPE_INVOKE_FUNCTION StepType = 5
)

// Enum value maps for StepType.
var (
	StepType_name = map[int32]string{
		0: "STEP_TYPE_UNSPECIFIED",
		1: "STEP_TYPE_INVOKE",
		2: "STEP_TYPE_SLEEP",
		3: "STEP_TYPE_WAIT_FOR_EVENT",
		4: "STEP_TYPE_COMPENSATE",
		5: "STEP_TYPE_INVOKE_FUNCTION",
	}
	StepType_value = map[string]int32{
		"STEP_TYPE_UNSPECIFIED":     0,
		"STEP_TYPE_INVOKE":          1,
		"STEP_TYPE_SLEEP":           2,
		"STEP_TYPE_WAIT_FOR_EVENT":  3,
		"STEP_TYPE_COMPENSATE":      4,
		"STEP_TYPE_INVOKE_FUNCTION": 5,
	}
)

func (x StepType) Enum() *StepType {
	p := new(StepType)
	*p = x
	return p
}

func (x StepType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepType) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_types_proto_enumTypes[4].Descriptor()
}

func (StepType) Type() protoreflect.EnumType {
	return &file_ironflow_v1_types_proto_enumTypes[4]
}

func (x StepType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepType.Descriptor instead.
func (StepType) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{4}
}

type Trigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event name pattern (e.g., "order.placed")
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Optional filter expression
	Expression string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	// Cron schedule expression (e.g., "0 9 * * *" for 9am daily)
	// When set, the function will be triggered on this schedule
	Cron          string `protobuf:"bytes,3,opt,name=cron,proto3" json:"cron,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_ironflow_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Trigger) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Trigger) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Trigger) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

type RetryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max attempts (default: 3)
	MaxAttempts int32 `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Initial delay in milliseconds (default: 1000)
	InitialDelayMs int32 `protobuf:"varint,2,opt,name=initial_delay_ms,json=initialDelayMs,proto3" json:"initial_delay_ms,omitempty"`
	// Backoff factor (default: 2.0)
	BackoffFactor float64 `protobuf:"fixed64,3,opt,name=backoff_factor,json=backoffFactor,proto3" json:"backoff_factor,omitempty"`
	// Max delay in milliseconds (default: 300000 = 5 min)
	MaxDelayMs    int32 `protobuf:"varint,4,opt,name=max_delay_ms,json=maxDelayMs,proto3" json:"max_delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	mi := &file_ironflow_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *RetryConfig) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryConfig) GetInitialDelayMs() int32 {
	if x != nil {
		return x.InitialDelayMs
	}
	return 0
}

func (x *RetryConfig) GetBackoffFactor() float64 {
	if x != nil {
		return x.BackoffFactor
	}
	return 0
}

func (x *RetryConfig) GetMaxDelayMs() int32 {
	if x != nil {
		return x.MaxDelayMs
	}
	return 0
}

type ConcurrencyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max concurrent executions
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// JSON path for grouping (e.g., "event.data.customerId")
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcurrencyConfig) Reset() {
	*x = ConcurrencyConfig{}
	mi := &file_ironflow_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrencyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrencyConfig) ProtoMessage() {}

func (x *ConcurrencyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrencyConfig.ProtoReflect.Descriptor instead.
func (*ConcurrencyConfig) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ConcurrencyConfig) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ConcurrencyConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// CancelOnSpec declares an event match that auto-cancels a running
// workflow when a matching event arrives. Multiple specs OR together —
// any match fires cancel. Issue #546 P3 / #572.
type CancelOnSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event name to match (e.g., "order.cancelled").
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// JSON-path expression that must equal the triggering run's
	// corresponding field. See internal/eventpath for path syntax.
	Match         string `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOnSpec) Reset() {
	*x = CancelOnSpec{}
	mi := &file_ironflow_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOnSpec) ProtoMessage() {}

func (x *CancelOnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOnSpec.ProtoReflect.Descriptor instead.
func (*CancelOnSpec) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOnSpec) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *CancelOnSpec) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

// DebounceConfig collapses rapid-fire events into a single invocation
// after a quiet period. First event arms a timer keyed by `key`
// (extracted via internal/eventpath). Subsequent events on the same key
// reset the timer and replace the payload. Handler fires once with the
// latest payload when the quiet period elapses. Issue #545.
type DebounceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quiet period in milliseconds. Must be >= 1000 (scheduler tick floor).
	PeriodMs int32 `protobuf:"varint,1,opt,name=period_ms,json=periodMs,proto3" json:"period_ms,omitempty"`
	// JSON-path expression for the debounce group key (e.g. "userId",
	// "data.customerId"). Empty-payload events use a global sentinel.
	// See internal/eventpath for path syntax.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebounceConfig) Reset() {
	*x = DebounceConfig{}
	mi := &file_ironflow_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebounceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebounceConfig) ProtoMessage() {}

func (x *DebounceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebounceConfig.ProtoReflect.Descriptor instead.
func (*DebounceConfig) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *DebounceConfig) GetPeriodMs() int32 {
	if x != nil {
		return x.PeriodMs
	}
	return 0
}

func (x *DebounceConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Function struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User-defined function ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Event triggers
	Triggers []*Trigger `protobuf:"bytes,4,rep,name=triggers,proto3" json:"triggers,omitempty"`
	// Retry configuration
	Retry *RetryConfig `protobuf:"bytes,5,opt,name=retry,proto3" json:"retry,omitempty"`
	// Timeout in milliseconds (default: 600000 = 10 min)
	TimeoutMs int32 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Concurrency configuration
	Concurrency *ConcurrencyConfig `protobuf:"bytes,7,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// Preferred execution mode
	PreferredMode ExecutionMode `protobuf:"varint,8,opt,name=preferred_mode,json=preferredMode,proto3,enum=ironflow.v1.ExecutionMode" json:"preferred_mode,omitempty"`
	// For Push mode
	EndpointUrl string `protobuf:"bytes,9,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	// JSON path for sticky routing
	ActorKey string `protobuf:"bytes,10,opt,name=actor_key,json=actorKey,proto3" json:"actor_key,omitempty"`
	// Status
	Status FunctionStatus `protobuf:"varint,11,opt,name=status,proto3,enum=ironflow.v1.FunctionStatus" json:"status,omitempty"`
	// Version number
	Version int32 `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Whether audit recording is enabled
	Recording bool `protobuf:"varint,15,opt,name=recording,proto3" json:"recording,omitempty"`
	// Retention period for audit events (e.g. "7d", "30d", "90d", "forever")
	RecordingRetention string `protobuf:"bytes,16,opt,name=recording_retention,json=recordingRetention,proto3" json:"recording_retention,omitempty"`
	// Arbitrary key-value metadata for the function
	Metadata *structpb.Struct `protobuf:"bytes,18,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Debounce configuration (optional). When set, events for this
	// function are collapsed per `debounce.key` and the handler fires
	// once per quiet-period. Issue #545.
	Debounce *DebounceConfig `protobuf:"bytes,19,opt,name=debounce,proto3" json:"debounce,omitempty"`
	// Cancel-on-event specs. When any spec matches an incoming event
	// and that event's match-path value equals the running run's
	// corresponding field, the run is auto-cancelled with cause
	// "cancel-on-event". Issue #546 P3 / #572.
	CancelOn      []*CancelOnSpec `protobuf:"bytes,21,rep,name=cancel_on,json=cancelOn,proto3" json:"cancel_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_ironflow_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Function) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *Function) GetRetry() *RetryConfig {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Function) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Function) GetConcurrency() *ConcurrencyConfig {
	if x != nil {
		return x.Concurrency
	}
	return nil
}

func (x *Function) GetPreferredMode() ExecutionMode {
	if x != nil {
		return x.PreferredMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *Function) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *Function) GetActorKey() string {
	if x != nil {
		return x.ActorKey
	}
	return ""
}

func (x *Function) GetStatus() FunctionStatus {
	if x != nil {
		return x.Status
	}
	return FunctionStatus_FUNCTION_STATUS_UNSPECIFIED
}

func (x *Function) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Function) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Function) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Function) GetRecording() bool {
	if x != nil {
		return x.Recording
	}
	return false
}

func (x *Function) GetRecordingRetention() string {
	if x != nil {
		return x.RecordingRetention
	}
	return ""
}

func (x *Function) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Function) GetDebounce() *DebounceConfig {
	if x != nil {
		return x.Debounce
	}
	return nil
}

func (x *Function) GetCancelOn() []*CancelOnSpec {
	if x != nil {
		return x.CancelOn
	}
	return nil
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Event name (e.g., "order.placed")
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Event payload
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Set ONLY when the payload is not a JSON object, which data cannot
	// represent (#1963). Readers take this when present and fall back to
	// data, so an object costs no extra bytes and old clients are
	// unaffected.
	DataValue *structpb.Value `protobuf:"bytes,12,opt,name=data_value,json=dataValue,proto3" json:"data_value,omitempty"`
	// Optional deduplication key
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Origin (webhook, sdk, api)
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Event timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Headers, user agent, etc.
	Metadata *structpb.Struct `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Schema version (default 1)
	Version int32 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	// Entity stream fields (empty for non-entity events)
	EntityId      string `protobuf:"bytes,9,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string `protobuf:"bytes,10,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityVersion int64  `protobuf:"varint,11,opt,name=entity_version,json=entityVersion,proto3" json:"entity_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ironflow_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetDataValue() *structpb.Value {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *Event) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Event) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Event) GetEntityVersion() int64 {
	if x != nil {
		return x.EntityVersion
	}
	return 0
}

type Run struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Run ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Function ID
	FunctionId string `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// Event ID that triggered this run
	EventId string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Execution mode used
	ExecutionMode ExecutionMode `protobuf:"varint,4,opt,name=execution_mode,json=executionMode,proto3,enum=ironflow.v1.ExecutionMode" json:"execution_mode,omitempty"`
	// Worker ID (for pull mode)
	WorkerId string `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Actor ID (for sticky routing)
	ActorId string `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Input data
	Input *structpb.Struct `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	// Set ONLY when the payload is not a JSON object, which input cannot
	// represent (#1963). Readers take this when present and fall back to
	// input, so an object costs no extra bytes and old clients are
	// unaffected.
	InputValue *structpb.Value `protobuf:"bytes,22,opt,name=input_value,json=inputValue,proto3" json:"input_value,omitempty"`
	// Output data
	Output *structpb.Struct `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`
	// Set ONLY when the payload is not a JSON object, which output cannot
	// represent (#1963). Readers take this when present and fall back to
	// output, so an object costs no extra bytes and old clients are
	// unaffected.
	OutputValue *structpb.Value `protobuf:"bytes,23,opt,name=output_value,json=outputValue,proto3" json:"output_value,omitempty"`
	// Error details if failed
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	// Current status
	Status RunStatus `protobuf:"varint,10,opt,name=status,proto3,enum=ironflow.v1.RunStatus" json:"status,omitempty"`
	// Current attempt number
	Attempt int32 `protobuf:"varint,11,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Max attempts allowed
	MaxAttempts int32 `protobuf:"varint,12,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// When execution started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When execution ended
	EndedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Whether a pause has been requested at the next step boundary
	PauseRequested bool `protobuf:"varint,19,opt,name=pause_requested,json=pauseRequested,proto3" json:"pause_requested,omitempty"`
	// Reason for current pause ("injection", "sleep", "wait_event", "")
	PauseReason string `protobuf:"bytes,20,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`
	// Function version at the time the run was created
	FunctionVersion int32 `protobuf:"varint,21,opt,name=function_version,json=functionVersion,proto3" json:"function_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_ironflow_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *Run) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Run) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *Run) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Run) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Run) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Run) GetInputValue() *structpb.Value {
	if x != nil {
		return x.InputValue
	}
	return nil
}

func (x *Run) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Run) GetOutputValue() *structpb.Value {
	if x != nil {
		return x.OutputValue
	}
	return nil
}

func (x *Run) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Run) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *Run) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Run) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Run) GetPauseRequested() bool {
	if x != nil {
		return x.PauseRequested
	}
	return false
}

func (x *Run) GetPauseReason() string {
	if x != nil {
		return x.PauseReason
	}
	return ""
}

func (x *Run) GetFunctionVersion() int32 {
	if x != nil {
		return x.FunctionVersion
	}
	return 0
}

type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Step record ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Run ID
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// User-defined step name
	StepId string `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Step type
	StepType StepType `protobuf:"varint,4,opt,name=step_type,json=stepType,proto3,enum=ironflow.v1.StepType" json:"step_type,omitempty"`
	// Execution sequence
	Sequence int32 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Current status
	Status StepStatus `protobuf:"varint,6,opt,name=status,proto3,enum=ironflow.v1.StepStatus" json:"status,omitempty"`
	// Input data
	Input *structpb.Struct `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	// Set ONLY when the payload is not a JSON object, which input cannot
	// represent (#1963). Readers take this when present and fall back to
	// input, so an object costs no extra bytes and old clients are
	// unaffected.
	InputValue *structpb.Value `protobuf:"bytes,19,opt,name=input_value,json=inputValue,proto3" json:"input_value,omitempty"`
	// Hash of input for memoization
	InputHash string `protobuf:"bytes,8,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	// Output data
	Output *structpb.Struct `protobuf:"bytes,9,opt,name=output,proto3" json:"output,omitempty"`
	// Set ONLY when the payload is not a JSON object, which output cannot
	// represent (#1963). Readers take this when present and fall back to
	// output, so an object costs no extra bytes and old clients are
	// unaffected.
	OutputValue *structpb.Value `protobuf:"bytes,20,opt,name=output_value,json=outputValue,proto3" json:"output_value,omitempty"`
	// Error details if failed
	Error *Error `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	// Current attempt number
	Attempt int32 `protobuf:"varint,11,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Execution duration in milliseconds
	DurationMs int32 `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// When step started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When step ended
	EndedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	// For patched steps - original output
	OriginalOutput *structpb.Struct `protobuf:"bytes,15,opt,name=original_output,json=originalOutput,proto3" json:"original_output,omitempty"`
	// Set ONLY when the payload is not a JSON object, which original_output cannot
	// represent (#1963). Readers take this when present and fall back to
	// original_output, so an object costs no extra bytes and old clients are
	// unaffected.
	OriginalOutputValue *structpb.Value `protobuf:"bytes,21,opt,name=original_output_value,json=originalOutputValue,proto3" json:"original_output_value,omitempty"`
	// When the step was patched
	PatchedAt *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=patched_at,json=patchedAt,proto3" json:"patched_at,omitempty"`
	// Who patched the step
	PatchedBy string `protobuf:"bytes,17,opt,name=patched_by,json=patchedBy,proto3" json:"patched_by,omitempty"`
	// For compensation steps: the step_id of the original step being compensated
	CompensationFor string `protobuf:"bytes,18,opt,name=compensation_for,json=compensationFor,proto3" json:"compensation_for,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_ironflow_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Step) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Step) GetStepType() StepType {
	if x != nil {
		return x.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (x *Step) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Step) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *Step) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Step) GetInputValue() *structpb.Value {
	if x != nil {
		return x.InputValue
	}
	return nil
}

func (x *Step) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *Step) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Step) GetOutputValue() *structpb.Value {
	if x != nil {
		return x.OutputValue
	}
	return nil
}

func (x *Step) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Step) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Step) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Step) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Step) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Step) GetOriginalOutput() *structpb.Struct {
	if x != nil {
		return x.OriginalOutput
	}
	return nil
}

func (x *Step) GetOriginalOutputValue() *structpb.Value {
	if x != nil {
		return x.OriginalOutputValue
	}
	return nil
}

func (x *Step) GetPatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PatchedAt
	}
	return nil
}

func (x *Step) GetPatchedBy() string {
	if x != nil {
		return x.PatchedBy
	}
	return ""
}

func (x *Step) GetCompensationFor() string {
	if x != nil {
		return x.CompensationFor
	}
	return ""
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Error code
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Stack trace
	Stack string `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"`
	// Whether the error is retryable
	Retryable bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Additional error details
	Details       *structpb.Struct `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_ironflow_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// ErrorInfo for detailed error responses
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of resource (function, run, step, event)
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// Resource identifier
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_ironflow_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorInfo) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ErrorInfo) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ErrorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_ironflow_v1_types_proto protoreflect.FileDescriptor

const file_ironflow_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x17ironflow/v1/types.proto\x12\vironflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"S\n" +
	"\aTrigger\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x12\n" +
	"\x04cron\x18\x03 \x01(\tR\x04cron\"\xa3\x01\n" +
	"\vRetryConfig\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12(\n" +
	"\x10initial_delay_ms\x18\x02 \x01(\x05R\x0einitialDelayMs\x12%\n" +
	"\x0ebackoff_factor\x18\x03 \x01(\x01R\rbackoffFactor\x12 \n" +
	"\fmax_delay_ms\x18\x04 \x01(\x05R\n" +
	"maxDelayMs\";\n" +
	"\x11ConcurrencyConfig\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\":\n" +
	"\fCancelOnSpec\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x14\n" +
	"\x05match\x18\x02 \x01(\tR\x05match\"?\n" +
	"\x0eDebounceConfig\x12\x1b\n" +
	"\tperiod_ms\x18\x01 \x01(\x05R\bperiodMs\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x82\a\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\btriggers\x18\x04 \x03(\v2\x14.ironflow.v1.TriggerR\btriggers\x12.\n" +
	"\x05retry\x18\x05 \x01(\v2\x18.ironflow.v1.RetryConfigR\x05retry\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\x12@\n" +
	"\vconcurrency\x18\a \x01(\v2\x1e.ironflow.v1.ConcurrencyConfigR\vconcurrency\x12A\n" +
	"\x0epreferred_mode\x18\b \x01(\x0e2\x1a.ironflow.v1.ExecutionModeR\rpreferredMode\x12!\n" +
	"\fendpoint_url\x18\t \x01(\tR\vendpointUrl\x12\x1b\n" +
	"\tactor_key\x18\n" +
	" \x01(\tR\bactorKey\x123\n" +
	"\x06status\x18\v \x01(\x0e2\x1b.ironflow.v1.FunctionStatusR\x06status\x12\x18\n" +
	"\aversion\x18\f \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\trecording\x18\x0f \x01(\bR\trecording\x12/\n" +
	"\x13recording_retention\x18\x10 \x01(\tR\x12recordingRetention\x123\n" +
	"\bmetadata\x18\x12 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x127\n" +
	"\bdebounce\x18\x13 \x01(\v2\x1b.ironflow.v1.DebounceConfigR\bdebounce\x126\n" +
	"\tcancel_on\x18\x15 \x03(\v2\x19.ironflow.v1.CancelOnSpecR\bcancelOnJ\x04\b\x11\x10\x12J\x04\b\x14\x10\x15R\x0epause_behaviorR\x14compensate_on_cancel\"\xbe\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x125\n" +
	"\n" +
	"data_value\x18\f \x01(\v2\x16.google.protobuf.ValueR\tdataValue\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12\x1b\n" +
	"\tentity_id\x18\t \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\n" +
	" \x01(\tR\n" +
	"entityType\x12%\n" +
	"\x0eentity_version\x18\v \x01(\x03R\rentityVersion\"\xbd\a\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\tR\n" +
	"functionId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12A\n" +
	"\x0eexecution_mode\x18\x04 \x01(\x0e2\x1a.ironflow.v1.ExecutionModeR\rexecutionMode\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12-\n" +
	"\x05input\x18\a \x01(\v2\x17.google.protobuf.StructR\x05input\x127\n" +
	"\vinput_value\x18\x16 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"inputValue\x12/\n" +
	"\x06output\x18\b \x01(\v2\x17.google.protobuf.StructR\x06output\x129\n" +
	"\foutput_value\x18\x17 \x01(\v2\x16.google.protobuf.ValueR\voutputValue\x12(\n" +
	"\x05error\x18\t \x01(\v2\x12.ironflow.v1.ErrorR\x05error\x12.\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x16.ironflow.v1.RunStatusR\x06status\x12\x18\n" +
	"\aattempt\x18\v \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\f \x01(\x05R\vmaxAttempts\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0fpause_requested\x18\x13 \x01(\bR\x0epauseRequested\x12!\n" +
	"\fpause_reason\x18\x14 \x01(\tR\vpauseReason\x12)\n" +
	"\x10function_version\x18\x15 \x01(\x05R\x0ffunctionVersionJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11R\x0fconcurrency_keyR\bpriority\"\xa4\a\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x122\n" +
	"\tstep_type\x18\x04 \x01(\x0e2\x15.ironflow.v1.StepTypeR\bstepType\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x05R\bsequence\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.ironflow.v1.StepStatusR\x06status\x12-\n" +
	"\x05input\x18\a \x01(\v2\x17.google.protobuf.StructR\x05input\x127\n" +
	"\vinput_value\x18\x13 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"inputValue\x12\x1d\n" +
	"\n" +
	"input_hash\x18\b \x01(\tR\tinputHash\x12/\n" +
	"\x06output\x18\t \x01(\v2\x17.google.protobuf.StructR\x06output\x129\n" +
	"\foutput_value\x18\x14 \x01(\v2\x16.google.protobuf.ValueR\voutputValue\x12(\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x12.ironflow.v1.ErrorR\x05error\x12\x18\n" +
	"\aattempt\x18\v \x01(\x05R\aattempt\x12\x1f\n" +
	"\vduration_ms\x18\f \x01(\x05R\n" +
	"durationMs\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12@\n" +
	"\x0foriginal_output\x18\x0f \x01(\v2\x17.google.protobuf.StructR\x0eoriginalOutput\x12J\n" +
	"\x15original_output_value\x18\x15 \x01(\v2\x16.google.protobuf.ValueR\x13originalOutputValue\x129\n" +
	"\n" +
	"patched_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tpatchedAt\x12\x1d\n" +
	"\n" +
	"patched_by\x18\x11 \x01(\tR\tpatchedBy\x12)\n" +
	"\x10compensation_for\x18\x12 \x01(\tR\x0fcompensationFor\"\x9c\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\tR\x05stack\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x121\n" +
	"\adetails\x18\x05 \x01(\v2\x17.google.protobuf.StructR\adetails\"\xd0\x01\n" +
	"\tErrorInfo\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.ironflow.v1.ErrorInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x87\x01\n" +
	"\x0eFunctionStatus\x12\x1f\n" +
	"\x1bFUNCTION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FUNCTION_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16FUNCTION_STATUS_PAUSED\x10\x02\x12\x1c\n" +
	"\x18FUNCTION_STATUS_ARCHIVED\x10\x03*a\n" +
	"\rExecutionMode\x12\x1e\n" +
	"\x1aEXECUTION_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXECUTION_MODE_PUSH\x10\x01\x12\x17\n" +
	"\x13EXECUTION_MODE_PULL\x10\x02*\xf8\x01\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUN_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14RUN_STATUS_CANCELLED\x10\x05\x12\x15\n" +
	"\x11RUN_STATUS_PAUSED\x10\x06\x12#\n" +
	"\x1fRUN_STATUS_WAITING_FOR_CAPACITY\x10\a\x12\x16\n" +
	"\x12RUN_STATUS_WAITING\x10\b\"\x04\b\x01\x10\x01*\x12RUN_STATUS_PENDING*\x8c\x02\n" +
	"\n" +
	"StepStatus\x12\x1b\n" +
	"\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STEP_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13STEP_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15STEP_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14STEP_STATUS_SLEEPING\x10\x05\x12\x17\n" +
	"\x13STEP_STATUS_WAITING\x10\x06\x12\x19\n" +
	"\x15STEP_STATUS_TIMED_OUT\x10\a\x12\x18\n" +
	"\x14STEP_STATUS_RETRYING\x10\b\x12\x14\n" +
	"\x10STEP_STATUS_DEAD\x10\t*\xa7\x01\n" +
	"\bStepType\x12\x19\n" +
	"\x15STEP_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STEP_TYPE_INVOKE\x10\x01\x12\x13\n" +
	"\x0fSTEP_TYPE_SLEEP\x10\x02\x12\x1c\n" +
	"\x18STEP_TYPE_WAIT_FOR_EVENT\x10\x03\x12\x18\n" +
	"\x14STEP_TYPE_COMPENSATE\x10\x04\x12\x1d\n" +
	"\x19STEP_TYPE_INVOKE_FUNCTION\x10\x05B:Z8github.com/sahina/ironflow-go/api/ironflow/v1;ironflowv1b\x06proto3"

var (
	file_ironflow_v1_types_proto_rawDescOnce sync.Once
	file_ironflow_v1_types_proto_rawDescData []byte
)

func file_ironflow_v1_types_proto_rawDescGZIP() []byte {
	file_ironflow_v1_types_proto_rawDescOnce.Do(func() {
		file_ironflow_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironflow_v1_types_proto_rawDesc), len(file_ironflow_v1_types_proto_rawDesc)))
	})
	return file_ironflow_v1_types_proto_rawDescData
}

var file_ironflow_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ironflow_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ironflow_v1_types_proto_goTypes = []any{
	(FunctionStatus)(0),           // 0: ironflow.v1.FunctionStatus
	(ExecutionMode)(0),            // 1: ironflow.v1.ExecutionMode
	(RunStatus)(0),                // 2: ironflow.v1.RunStatus
	(StepStatus)(0),               // 3: ironflow.v1.StepStatus
	(StepType)(0),                 // 4: ironflow.v1.StepType
	(*Trigger)(nil),               // 5: ironflow.v1.Trigger
	(*RetryConfig)(nil),           // 6: ironflow.v1.RetryConfig
	(*ConcurrencyConfig)(nil),     // 7: ironflow.v1.ConcurrencyConfig
	(*CancelOnSpec)(nil),          // 8: ironflow.v1.CancelOnSpec
	(*DebounceConfig)(nil),        // 9: ironflow.v1.DebounceConfig
	(*Function)(nil),              // 10: ironflow.v1.Function
	(*Event)(nil),                 // 11: ironflow.v1.Event
	(*Run)(nil),                   // 12: ironflow.v1.Run
	(*Step)(nil),                  // 13: ironflow.v1.Step
	(*Error)(nil),                 // 14: ironflow.v1.Error
	(*ErrorInfo)(nil),             // 15: ironflow.v1.ErrorInfo
	nil,                           // 16: ironflow.v1.ErrorInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
	(*structpb.Value)(nil),        // 19: google.protobuf.Value
}
var file_ironflow_v1_types_proto_depIdxs = []int32{
	5,  // 0: ironflow.v1.Function.triggers:type_name -> ironflow.v1.Trigger
	6,  // 1: ironflow.v1.Function.retry:type_name -> ironflow.v1.RetryConfig
	7,  // 2: ironflow.v1.Function.concurrency:type_name -> ironflow.v1.ConcurrencyConfig
	1,  // 3: ironflow.v1.Function.preferred_mode:type_name -> ironflow.v1.ExecutionMode
	0,  // 4: ironflow.v1.Function.status:type_name -> ironflow.v1.FunctionStatus
	17, // 5: ironflow.v1.Function.created_at:type_name -> google.protobuf.Timestamp
	17, // 6: ironflow.v1.Function.updated_at:type_name -> google.protobuf.Timestamp
	18, // 7: ironflow.v1.Function.metadata:type_name -> google.protobuf.Struct
	9,  // 8: ironflow.v1.Function.debounce:type_name -> ironflow.v1.DebounceConfig
	8,  // 9: ironflow.v1.Function.cancel_on:type_name -> ironflow.v1.CancelOnSpec
	18, // 10: ironflow.v1.Event.data:type_name -> google.protobuf.Struct
	19, // 11: ironflow.v1.Event.data_value:type_name -> google.protobuf.Value
	17, // 12: ironflow.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	18, // 13: ironflow.v1.Event.metadata:type_name -> google.protobuf.Struct
	1,  // 14: ironflow.v1.Run.execution_mode:type_name -> ironflow.v1.ExecutionMode
	18, // 15: ironflow.v1.Run.input:type_name -> google.protobuf.Struct
	19, // 16: ironflow.v1.Run.input_value:type_name -> google.protobuf.Value
	18, // 17: ironflow.v1.Run.output:type_name -> google.protobuf.Struct
	19, // 18: ironflow.v1.Run.output_value:type_name -> google.protobuf.Value
	14, // 19: ironflow.v1.Run.error:type_name -> ironflow.v1.Error
	2,  // 20: ironflow.v1.Run.status:type_name -> ironflow.v1.RunStatus
	17, // 21: ironflow.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	17, // 22: ironflow.v1.Run.ended_at:type_name -> google.protobuf.Timestamp
	17, // 23: ironflow.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	17, // 24: ironflow.v1.Run.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 25: ironflow.v1.Step.step_type:type_name -> ironflow.v1.StepType
	3,  // 26: ironflow.v1.Step.status:type_name -> ironflow.v1.StepStatus
	18, // 27: ironflow.v1.Step.input:type_name -> google.protobuf.Struct
	19, // 28: ironflow.v1.Step.input_value:type_name -> google.protobuf.Value
	18, // 29: ironflow.v1.Step.output:type_name -> google.protobuf.Struct
	19, // 30: ironflow.v1.Step.output_value:type_name -> google.protobuf.Value
	14, // 31: ironflow.v1.Step.error:type_name -> ironflow.v1.Error
	17, // 32: ironflow.v1.Step.started_at:type_name -> google.protobuf.Timestamp
	17, // 33: ironflow.v1.Step.ended_at:type_name -> google.protobuf.Timestamp
	18, // 34: ironflow.v1.Step.original_output:type_name -> google.protobuf.Struct
	19, // 35: ironflow.v1.Step.original_output_value:type_name -> google.protobuf.Value
	17, // 36: ironflow.v1.Step.patched_at:type_name -> google.protobuf.Timestamp
	18, // 37: ironflow.v1.Error.details:type_name -> google.protobuf.Struct
	16, // 38: ironflow.v1.ErrorInfo.metadata:type_name -> ironflow.v1.ErrorInfo.MetadataEntry
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_ironflow_v1_types_proto_init() }
func file_ironflow_v1_types_proto_init() {
	if File_ironflow_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironflow_v1_types_proto_rawDesc), len(file_ironflow_v1_types_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ironflow_v1_types_proto_goTypes,
		DependencyIndexes: file_ironflow_v1_types_proto_depIdxs,
		EnumInfos:         file_ironflow_v1_types_proto_enumTypes,
		MessageInfos:      file_ironflow_v1_types_proto_msgTypes,
	}.Build()
	File_ironflow_v1_types_proto = out.File
	file_ironflow_v1_types_proto_goTypes = nil
	file_ironflow_v1_types_proto_depIdxs = nil
}
