// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironflow/v1/worker.proto

package ironflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseState int32

const (
	LeaseState_LEASE_STATE_UNSPECIFIED LeaseState = 0
	// Lease extended; keep executing.
	LeaseState_LEASE_STATE_REFRESHED LeaseState = 1
	// Tuple matched no live lease (expired/recovered/superseded) — cancel locally.
	LeaseState_LEASE_STATE_STALE LeaseState = 2
	// Engine has no record of this segment — cancel locally.
	LeaseState_LEASE_STATE_UNKNOWN LeaseState = 3
)

// Enum value maps for LeaseState.
var (
	LeaseState_name = map[int32]string{
		0: "LEASE_STATE_UNSPECIFIED",
		1: "LEASE_STATE_REFRESHED",
		2: "LEASE_STATE_STALE",
		3: "LEASE_STATE_UNKNOWN",
	}
	LeaseState_value = map[string]int32{
		"LEASE_STATE_UNSPECIFIED": 0,
		"LEASE_STATE_REFRESHED":   1,
		"LEASE_STATE_STALE":       2,
		"LEASE_STATE_UNKNOWN":     3,
	}
)

func (x LeaseState) Enum() *LeaseState {
	p := new(LeaseState)
	*p = x
	return p
}

func (x LeaseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseState) Descriptor() protoreflect.EnumDescriptor {
	return file_ironflow_v1_worker_proto_enumTypes[0].Descriptor()
}

func (LeaseState) Type() protoreflect.EnumType {
	return &file_ironflow_v1_worker_proto_enumTypes[0]
}

func (x LeaseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseState.Descriptor instead.
func (LeaseState) EnumDescriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{0}
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_StepStarted
	//	*WorkerMessage_StepCompleted
	//	*WorkerMessage_StepFailed
	//	*WorkerMessage_StepYielded
	//	*WorkerMessage_JobCompleted
	//	*WorkerMessage_JobFailed
	//	*WorkerMessage_JobAck
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *WorkerRegister {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *WorkerHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetStepStarted() *StepStarted {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_StepStarted); ok {
			return x.StepStarted
		}
	}
	return nil
}

func (x *WorkerMessage) GetStepCompleted() *StepCompleted {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_StepCompleted); ok {
			return x.StepCompleted
		}
	}
	return nil
}

func (x *WorkerMessage) GetStepFailed() *StepFailed {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_StepFailed); ok {
			return x.StepFailed
		}
	}
	return nil
}

func (x *WorkerMessage) GetStepYielded() *StepYielded {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_StepYielded); ok {
			return x.StepYielded
		}
	}
	return nil
}

func (x *WorkerMessage) GetJobCompleted() *JobCompleted {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_JobCompleted); ok {
			return x.JobCompleted
		}
	}
	return nil
}

func (x *WorkerMessage) GetJobFailed() *JobFailed {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_JobFailed); ok {
			return x.JobFailed
		}
	}
	return nil
}

func (x *WorkerMessage) GetJobAck() *JobAck {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_JobAck); ok {
			return x.JobAck
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *WorkerRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *WorkerHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_StepStarted struct {
	StepStarted *StepStarted `protobuf:"bytes,3,opt,name=step_started,json=stepStarted,proto3,oneof"`
}

type WorkerMessage_StepCompleted struct {
	StepCompleted *StepCompleted `protobuf:"bytes,4,opt,name=step_completed,json=stepCompleted,proto3,oneof"`
}

type WorkerMessage_StepFailed struct {
	StepFailed *StepFailed `protobuf:"bytes,5,opt,name=step_failed,json=stepFailed,proto3,oneof"`
}

type WorkerMessage_StepYielded struct {
	StepYielded *StepYielded `protobuf:"bytes,6,opt,name=step_yielded,json=stepYielded,proto3,oneof"`
}

type WorkerMessage_JobCompleted struct {
	JobCompleted *JobCompleted `protobuf:"bytes,7,opt,name=job_completed,json=jobCompleted,proto3,oneof"`
}

type WorkerMessage_JobFailed struct {
	JobFailed *JobFailed `protobuf:"bytes,8,opt,name=job_failed,json=jobFailed,proto3,oneof"`
}

type WorkerMessage_JobAck struct {
	JobAck *JobAck `protobuf:"bytes,9,opt,name=job_ack,json=jobAck,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_StepStarted) isWorkerMessage_Payload() {}

func (*WorkerMessage_StepCompleted) isWorkerMessage_Payload() {}

func (*WorkerMessage_StepFailed) isWorkerMessage_Payload() {}

func (*WorkerMessage_StepYielded) isWorkerMessage_Payload() {}

func (*WorkerMessage_JobCompleted) isWorkerMessage_Payload() {}

func (*WorkerMessage_JobFailed) isWorkerMessage_Payload() {}

func (*WorkerMessage_JobAck) isWorkerMessage_Payload() {}

type WorkerRegister struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Functions this worker handles
	FunctionIds       []string `protobuf:"bytes,3,rep,name=function_ids,json=functionIds,proto3" json:"function_ids,omitempty"`
	MaxConcurrentJobs int32    `protobuf:"varint,4,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	// e.g., {"gpu": "nvidia-a100"}
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       *WorkerVersion    `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegister) Reset() {
	*x = WorkerRegister{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegister) ProtoMessage() {}

func (x *WorkerRegister) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegister.ProtoReflect.Descriptor instead.
func (*WorkerRegister) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerRegister) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegister) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerRegister) GetFunctionIds() []string {
	if x != nil {
		return x.FunctionIds
	}
	return nil
}

func (x *WorkerRegister) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *WorkerRegister) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkerRegister) GetVersion() *WorkerVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type WorkerVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdk           string                 `protobuf:"bytes,1,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Runtime       string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerVersion) Reset() {
	*x = WorkerVersion{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerVersion) ProtoMessage() {}

func (x *WorkerVersion) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerVersion.ProtoReflect.Descriptor instead.
func (*WorkerVersion) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerVersion) GetSdk() string {
	if x != nil {
		return x.Sdk
	}
	return ""
}

func (x *WorkerVersion) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type WorkerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveJobs    int32                  `protobuf:"varint,2,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	Jobs          []*ActiveJob           `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Metrics       *WorkerMetrics         `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerHeartbeat) GetJobs() []*ActiveJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *WorkerHeartbeat) GetMetrics() *WorkerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ActiveJob struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	JobId     string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Execution fence (#1206, ADR 0037). A heartbeat reports the active
	// (run_id, execution_seq, lease_token) tuple per job so the engine can
	// batch-refresh matching leases and answer refreshed|stale|unknown.
	RunId         string `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExecutionSeq  int64  `protobuf:"varint,4,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string `protobuf:"bytes,5,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveJob) Reset() {
	*x = ActiveJob{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveJob) ProtoMessage() {}

func (x *ActiveJob) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveJob.ProtoReflect.Descriptor instead.
func (*ActiveJob) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ActiveJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ActiveJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ActiveJob) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ActiveJob) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *ActiveJob) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type WorkerMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	JobsCompleted int64                  `protobuf:"varint,3,opt,name=jobs_completed,json=jobsCompleted,proto3" json:"jobs_completed,omitempty"`
	JobsFailed    int64                  `protobuf:"varint,4,opt,name=jobs_failed,json=jobsFailed,proto3" json:"jobs_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMetrics) Reset() {
	*x = WorkerMetrics{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMetrics) ProtoMessage() {}

func (x *WorkerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMetrics.ProtoReflect.Descriptor instead.
func (*WorkerMetrics) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *WorkerMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *WorkerMetrics) GetJobsCompleted() int64 {
	if x != nil {
		return x.JobsCompleted
	}
	return 0
}

func (x *WorkerMetrics) GetJobsFailed() int64 {
	if x != nil {
		return x.JobsFailed
	}
	return 0
}

type StepStarted struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId   string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StepType StepType               `protobuf:"varint,4,opt,name=step_type,json=stepType,proto3,enum=ironflow.v1.StepType" json:"step_type,omitempty"`
	// Execution fence (#1206, ADR 0037): every mutating worker message carries
	// (execution_seq, lease_token); a stale/superseded tuple is rejected.
	ExecutionSeq  int64  `protobuf:"varint,5,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string `protobuf:"bytes,6,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStarted) Reset() {
	*x = StepStarted{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStarted) ProtoMessage() {}

func (x *StepStarted) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStarted.ProtoReflect.Descriptor instead.
func (*StepStarted) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *StepStarted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepStarted) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepStarted) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepStarted) GetStepType() StepType {
	if x != nil {
		return x.StepType
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (x *StepStarted) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *StepStarted) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type StepCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExecutionSeq  int64                  `protobuf:"varint,5,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,6,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepCompleted) Reset() {
	*x = StepCompleted{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCompleted) ProtoMessage() {}

func (x *StepCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCompleted.ProtoReflect.Descriptor instead.
func (*StepCompleted) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *StepCompleted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepCompleted) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepCompleted) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *StepCompleted) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepCompleted) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *StepCompleted) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type StepFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExecutionSeq  int64                  `protobuf:"varint,5,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,6,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepFailed) Reset() {
	*x = StepFailed{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFailed) ProtoMessage() {}

func (x *StepFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFailed.ProtoReflect.Descriptor instead.
func (*StepFailed) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *StepFailed) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepFailed) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepFailed) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *StepFailed) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepFailed) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *StepFailed) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type StepYielded struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	JobId  string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Types that are valid to be assigned to YieldInfo:
	//
	//	*StepYielded_Sleep
	//	*StepYielded_WaitEvent
	YieldInfo     isStepYielded_YieldInfo `protobuf_oneof:"yield_info"`
	ExecutionSeq  int64                   `protobuf:"varint,5,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string                  `protobuf:"bytes,6,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepYielded) Reset() {
	*x = StepYielded{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepYielded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepYielded) ProtoMessage() {}

func (x *StepYielded) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepYielded.ProtoReflect.Descriptor instead.
func (*StepYielded) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *StepYielded) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepYielded) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepYielded) GetYieldInfo() isStepYielded_YieldInfo {
	if x != nil {
		return x.YieldInfo
	}
	return nil
}

func (x *StepYielded) GetSleep() *SleepYield {
	if x != nil {
		if x, ok := x.YieldInfo.(*StepYielded_Sleep); ok {
			return x.Sleep
		}
	}
	return nil
}

func (x *StepYielded) GetWaitEvent() *WaitEventYield {
	if x != nil {
		if x, ok := x.YieldInfo.(*StepYielded_WaitEvent); ok {
			return x.WaitEvent
		}
	}
	return nil
}

func (x *StepYielded) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *StepYielded) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type isStepYielded_YieldInfo interface {
	isStepYielded_YieldInfo()
}

type StepYielded_Sleep struct {
	Sleep *SleepYield `protobuf:"bytes,3,opt,name=sleep,proto3,oneof"`
}

type StepYielded_WaitEvent struct {
	WaitEvent *WaitEventYield `protobuf:"bytes,4,opt,name=wait_event,json=waitEvent,proto3,oneof"`
}

func (*StepYielded_Sleep) isStepYielded_YieldInfo() {}

func (*StepYielded_WaitEvent) isStepYielded_YieldInfo() {}

type SleepYield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepYield) Reset() {
	*x = SleepYield{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepYield) ProtoMessage() {}

func (x *SleepYield) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepYield.ProtoReflect.Descriptor instead.
func (*SleepYield) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *SleepYield) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type WaitEventYield struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventName       string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	MatchExpression string                 `protobuf:"bytes,2,opt,name=match_expression,json=matchExpression,proto3" json:"match_expression,omitempty"`
	MatchValue      string                 `protobuf:"bytes,3,opt,name=match_value,json=matchValue,proto3" json:"match_value,omitempty"`
	Timeout         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WaitEventYield) Reset() {
	*x = WaitEventYield{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitEventYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitEventYield) ProtoMessage() {}

func (x *WaitEventYield) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitEventYield.ProtoReflect.Descriptor instead.
func (*WaitEventYield) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *WaitEventYield) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *WaitEventYield) GetMatchExpression() string {
	if x != nil {
		return x.MatchExpression
	}
	return ""
}

func (x *WaitEventYield) GetMatchValue() string {
	if x != nil {
		return x.MatchValue
	}
	return ""
}

func (x *WaitEventYield) GetTimeout() *timestamppb.Timestamp {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type JobCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	DurationMs    int32                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExecutionSeq  int64                  `protobuf:"varint,4,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,5,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCompleted) Reset() {
	*x = JobCompleted{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompleted) ProtoMessage() {}

func (x *JobCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompleted.ProtoReflect.Descriptor instead.
func (*JobCompleted) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *JobCompleted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobCompleted) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *JobCompleted) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *JobCompleted) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *JobCompleted) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type JobFailed struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Error      *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs int32                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Steps executed during this invocation (includes compensation steps).
	// Populated only for terminal failures (non-retryable errors).
	Steps         []*ExecutedStep `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	ExecutionSeq  int64           `protobuf:"varint,5,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string          `protobuf:"bytes,6,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailed) Reset() {
	*x = JobFailed{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailed) ProtoMessage() {}

func (x *JobFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailed.ProtoReflect.Descriptor instead.
func (*JobFailed) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *JobFailed) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobFailed) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobFailed) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *JobFailed) GetSteps() []*ExecutedStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *JobFailed) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *JobFailed) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

// ExecutedStep carries the result of a step executed during a job invocation.
// Used in JobFailed to persist compensation steps when reporting terminal failures.
type ExecutedStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Step type: "invoke", "sleep", "wait_for_event", "compensate"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Step status: "completed", "failed"
	Status string           `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Output *structpb.Struct `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error  *Error           `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// For compensation steps: the step_id of the original step being compensated
	CompensationFor string `protobuf:"bytes,7,opt,name=compensation_for,json=compensationFor,proto3" json:"compensation_for,omitempty"`
	DurationMs      int32  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutedStep) Reset() {
	*x = ExecutedStep{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutedStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedStep) ProtoMessage() {}

func (x *ExecutedStep) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedStep.ProtoReflect.Descriptor instead.
func (*ExecutedStep) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutedStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutedStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecutedStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecutedStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutedStep) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecutedStep) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecutedStep) GetCompensationFor() string {
	if x != nil {
		return x.CompensationFor
	}
	return ""
}

func (x *ExecutedStep) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type JobAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Fenced assignment acknowledgement (#1206, ADR 0037): the worker echoes the
	// assignment's fence before executing user code; a stale/mismatched ack is
	// rejected and the segment is not executed.
	RunId         string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExecutionSeq  int64  `protobuf:"varint,3,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken    string `protobuf:"bytes,4,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAck) Reset() {
	*x = JobAck{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAck) ProtoMessage() {}

func (x *JobAck) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAck.ProtoReflect.Descriptor instead.
func (*JobAck) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{15}
}

func (x *JobAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAck) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobAck) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *JobAck) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type EngineMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EngineMessage_Registered
	//	*EngineMessage_Job
	//	*EngineMessage_StepAck
	//	*EngineMessage_Resume
	//	*EngineMessage_Cancel
	//	*EngineMessage_Shutdown
	//	*EngineMessage_LeaseRefresh
	Payload       isEngineMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineMessage) Reset() {
	*x = EngineMessage{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineMessage) ProtoMessage() {}

func (x *EngineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineMessage.ProtoReflect.Descriptor instead.
func (*EngineMessage) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{16}
}

func (x *EngineMessage) GetPayload() isEngineMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EngineMessage) GetRegistered() *WorkerRegistered {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *EngineMessage) GetJob() *JobAssignment {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_Job); ok {
			return x.Job
		}
	}
	return nil
}

func (x *EngineMessage) GetStepAck() *StepAck {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_StepAck); ok {
			return x.StepAck
		}
	}
	return nil
}

func (x *EngineMessage) GetResume() *ResumeJob {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *EngineMessage) GetCancel() *CancelJob {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *EngineMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *EngineMessage) GetLeaseRefresh() *LeaseRefreshResult {
	if x != nil {
		if x, ok := x.Payload.(*EngineMessage_LeaseRefresh); ok {
			return x.LeaseRefresh
		}
	}
	return nil
}

type isEngineMessage_Payload interface {
	isEngineMessage_Payload()
}

type EngineMessage_Registered struct {
	Registered *WorkerRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type EngineMessage_Job struct {
	Job *JobAssignment `protobuf:"bytes,2,opt,name=job,proto3,oneof"`
}

type EngineMessage_StepAck struct {
	StepAck *StepAck `protobuf:"bytes,3,opt,name=step_ack,json=stepAck,proto3,oneof"`
}

type EngineMessage_Resume struct {
	Resume *ResumeJob `protobuf:"bytes,4,opt,name=resume,proto3,oneof"`
}

type EngineMessage_Cancel struct {
	Cancel *CancelJob `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type EngineMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,6,opt,name=shutdown,proto3,oneof"`
}

type EngineMessage_LeaseRefresh struct {
	LeaseRefresh *LeaseRefreshResult `protobuf:"bytes,7,opt,name=lease_refresh,json=leaseRefresh,proto3,oneof"`
}

func (*EngineMessage_Registered) isEngineMessage_Payload() {}

func (*EngineMessage_Job) isEngineMessage_Payload() {}

func (*EngineMessage_StepAck) isEngineMessage_Payload() {}

func (*EngineMessage_Resume) isEngineMessage_Payload() {}

func (*EngineMessage_Cancel) isEngineMessage_Payload() {}

func (*EngineMessage_Shutdown) isEngineMessage_Payload() {}

func (*EngineMessage_LeaseRefresh) isEngineMessage_Payload() {}

// LeaseRefreshResult answers a heartbeat's reported active fence tuples
// (#1206, ADR 0037): the engine batch-refreshes the matching leases and returns
// one status per reported segment. The worker immediately cancels any segment
// that comes back STALE or UNKNOWN.
type LeaseRefreshResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentLeaseStatus  `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRefreshResult) Reset() {
	*x = LeaseRefreshResult{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRefreshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRefreshResult) ProtoMessage() {}

func (x *LeaseRefreshResult) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRefreshResult.ProtoReflect.Descriptor instead.
func (*LeaseRefreshResult) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{17}
}

func (x *LeaseRefreshResult) GetSegments() []*SegmentLeaseStatus {
	if x != nil {
		return x.Segments
	}
	return nil
}

type SegmentLeaseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExecutionSeq  int64                  `protobuf:"varint,2,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	State         LeaseState             `protobuf:"varint,3,opt,name=state,proto3,enum=ironflow.v1.LeaseState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentLeaseStatus) Reset() {
	*x = SegmentLeaseStatus{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentLeaseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentLeaseStatus) ProtoMessage() {}

func (x *SegmentLeaseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentLeaseStatus.ProtoReflect.Descriptor instead.
func (*SegmentLeaseStatus) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{18}
}

func (x *SegmentLeaseStatus) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SegmentLeaseStatus) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *SegmentLeaseStatus) GetState() LeaseState {
	if x != nil {
		return x.State
	}
	return LeaseState_LEASE_STATE_UNSPECIFIED
}

type WorkerRegistered struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Required heartbeat frequency in ms
	HeartbeatIntervalMs int32 `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkerRegistered) Reset() {
	*x = WorkerRegistered{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistered) ProtoMessage() {}

func (x *WorkerRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistered.ProtoReflect.Descriptor instead.
func (*WorkerRegistered) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{19}
}

func (x *WorkerRegistered) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistered) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type JobAssignment struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RunId      string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FunctionId string                 `protobuf:"bytes,3,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Event      *Event                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	// Memoized steps
	CompletedSteps []*CompletedStep `protobuf:"bytes,5,rep,name=completed_steps,json=completedSteps,proto3" json:"completed_steps,omitempty"`
	ActorId        string           `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Attempt        int32            `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Context        *JobContext      `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	// Execution fence (#1206, ADR 0037). The worker echoes execution_seq +
	// lease_token on its ack and on every mutating message; lease_expires_at is
	// database time, informational for the worker's local refresh cadence.
	ExecutionSeq   int64                  `protobuf:"varint,9,opt,name=execution_seq,json=executionSeq,proto3" json:"execution_seq,omitempty"`
	LeaseToken     string                 `protobuf:"bytes,10,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{20}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobAssignment) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *JobAssignment) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *JobAssignment) GetCompletedSteps() []*CompletedStep {
	if x != nil {
		return x.CompletedSteps
	}
	return nil
}

func (x *JobAssignment) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *JobAssignment) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobAssignment) GetContext() *JobContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *JobAssignment) GetExecutionSeq() int64 {
	if x != nil {
		return x.ExecutionSeq
	}
	return 0
}

func (x *JobAssignment) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *JobAssignment) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type CompletedStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedStep) Reset() {
	*x = CompletedStep{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedStep) ProtoMessage() {}

func (x *CompletedStep) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedStep.ProtoReflect.Descriptor instead.
func (*CompletedStep) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{21}
}

func (x *CompletedStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *CompletedStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompletedStep) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

type JobContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secrets       map[string]string      `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobContext) Reset() {
	*x = JobContext{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobContext) ProtoMessage() {}

func (x *JobContext) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobContext.ProtoReflect.Descriptor instead.
func (*JobContext) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{22}
}

func (x *JobContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *JobContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JobContext) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type StepAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepAck) Reset() {
	*x = StepAck{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepAck) ProtoMessage() {}

func (x *StepAck) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepAck.ProtoReflect.Descriptor instead.
func (*StepAck) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{23}
}

func (x *StepAck) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StepAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResumeJob struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	JobId  string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepId string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// "sleep" or "wait_event"
	ResumeType string `protobuf:"bytes,3,opt,name=resume_type,json=resumeType,proto3" json:"resume_type,omitempty"`
	// For wait_event: the received event
	ResumeData    *structpb.Struct `protobuf:"bytes,4,opt,name=resume_data,json=resumeData,proto3" json:"resume_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeJob) Reset() {
	*x = ResumeJob{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeJob) ProtoMessage() {}

func (x *ResumeJob) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeJob.ProtoReflect.Descriptor instead.
func (*ResumeJob) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{24}
}

func (x *ResumeJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResumeJob) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ResumeJob) GetResumeType() string {
	if x != nil {
		return x.ResumeType
	}
	return ""
}

func (x *ResumeJob) GetResumeData() *structpb.Struct {
	if x != nil {
		return x.ResumeData
	}
	return nil
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{25}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJob) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Shutdown struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// Time to complete active jobs
	DrainTimeoutMs int32 `protobuf:"varint,2,opt,name=drain_timeout_ms,json=drainTimeoutMs,proto3" json:"drain_timeout_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_ironflow_v1_worker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_ironflow_v1_worker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_ironflow_v1_worker_proto_rawDescGZIP(), []int{26}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Shutdown) GetDrainTimeoutMs() int32 {
	if x != nil {
		return x.DrainTimeoutMs
	}
	return 0
}

var File_ironflow_v1_worker_proto protoreflect.FileDescriptor

const file_ironflow_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x18ironflow/v1/worker.proto\x12\vironflow.v1\x1a\x17ironflow/v1/types.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x04\n" +
	"\rWorkerMessage\x129\n" +
	"\bregister\x18\x01 \x01(\v2\x1b.ironflow.v1.WorkerRegisterH\x00R\bregister\x12<\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1c.ironflow.v1.WorkerHeartbeatH\x00R\theartbeat\x12=\n" +
	"\fstep_started\x18\x03 \x01(\v2\x18.ironflow.v1.StepStartedH\x00R\vstepStarted\x12C\n" +
	"\x0estep_completed\x18\x04 \x01(\v2\x1a.ironflow.v1.StepCompletedH\x00R\rstepCompleted\x12:\n" +
	"\vstep_failed\x18\x05 \x01(\v2\x17.ironflow.v1.StepFailedH\x00R\n" +
	"stepFailed\x12=\n" +
	"\fstep_yielded\x18\x06 \x01(\v2\x18.ironflow.v1.StepYieldedH\x00R\vstepYielded\x12@\n" +
	"\rjob_completed\x18\a \x01(\v2\x19.ironflow.v1.JobCompletedH\x00R\fjobCompleted\x127\n" +
	"\n" +
	"job_failed\x18\b \x01(\v2\x16.ironflow.v1.JobFailedH\x00R\tjobFailed\x12.\n" +
	"\ajob_ack\x18\t \x01(\v2\x13.ironflow.v1.JobAckH\x00R\x06jobAckB\t\n" +
	"\apayload\"\xce\x02\n" +
	"\x0eWorkerRegister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\ffunction_ids\x18\x03 \x03(\tR\vfunctionIds\x12.\n" +
	"\x13max_concurrent_jobs\x18\x04 \x01(\x05R\x11maxConcurrentJobs\x12?\n" +
	"\x06labels\x18\x05 \x03(\v2'.ironflow.v1.WorkerRegister.LabelsEntryR\x06labels\x124\n" +
	"\aversion\x18\x06 \x01(\v2\x1a.ironflow.v1.WorkerVersionR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\rWorkerVersion\x12\x10\n" +
	"\x03sdk\x18\x01 \x01(\tR\x03sdk\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\"\xb1\x01\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vactive_jobs\x18\x02 \x01(\x05R\n" +
	"activeJobs\x12*\n" +
	"\x04jobs\x18\x03 \x03(\v2\x16.ironflow.v1.ActiveJobR\x04jobs\x124\n" +
	"\ametrics\x18\x04 \x01(\v2\x1a.ironflow.v1.WorkerMetricsR\ametrics\"\xba\x01\n" +
	"\tActiveJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12#\n" +
	"\rexecution_seq\x18\x04 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x05 \x01(\tR\n" +
	"leaseToken\"\x9f\x01\n" +
	"\rWorkerMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12%\n" +
	"\x0ejobs_completed\x18\x03 \x01(\x03R\rjobsCompleted\x12\x1f\n" +
	"\vjobs_failed\x18\x04 \x01(\x03R\n" +
	"jobsFailed\"\xcb\x01\n" +
	"\vStepStarted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\tstep_type\x18\x04 \x01(\x0e2\x15.ironflow.v1.StepTypeR\bstepType\x12#\n" +
	"\rexecution_seq\x18\x05 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x06 \x01(\tR\n" +
	"leaseToken\"\xd7\x01\n" +
	"\rStepCompleted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12/\n" +
	"\x06output\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x12#\n" +
	"\rexecution_seq\x18\x05 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x06 \x01(\tR\n" +
	"leaseToken\"\xcd\x01\n" +
	"\n" +
	"StepFailed\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x12.ironflow.v1.ErrorR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x12#\n" +
	"\rexecution_seq\x18\x05 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x06 \x01(\tR\n" +
	"leaseToken\"\x80\x02\n" +
	"\vStepYielded\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12/\n" +
	"\x05sleep\x18\x03 \x01(\v2\x17.ironflow.v1.SleepYieldH\x00R\x05sleep\x12<\n" +
	"\n" +
	"wait_event\x18\x04 \x01(\v2\x1b.ironflow.v1.WaitEventYieldH\x00R\twaitEvent\x12#\n" +
	"\rexecution_seq\x18\x05 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x06 \x01(\tR\n" +
	"leaseTokenB\f\n" +
	"\n" +
	"yield_info\">\n" +
	"\n" +
	"SleepYield\x120\n" +
	"\x05until\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\xb1\x01\n" +
	"\x0eWaitEventYield\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12)\n" +
	"\x10match_expression\x18\x02 \x01(\tR\x0fmatchExpression\x12\x1f\n" +
	"\vmatch_value\x18\x03 \x01(\tR\n" +
	"matchValue\x124\n" +
	"\atimeout\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\atimeout\"\xbd\x01\n" +
	"\fJobCompleted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x06output\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\x12#\n" +
	"\rexecution_seq\x18\x04 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x05 \x01(\tR\n" +
	"leaseToken\"\xe4\x01\n" +
	"\tJobFailed\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x12.ironflow.v1.ErrorR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\x12/\n" +
	"\x05steps\x18\x04 \x03(\v2\x19.ironflow.v1.ExecutedStepR\x05steps\x12#\n" +
	"\rexecution_seq\x18\x05 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x06 \x01(\tR\n" +
	"leaseToken\"\x85\x02\n" +
	"\fExecutedStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x06output\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06output\x12(\n" +
	"\x05error\x18\x06 \x01(\v2\x12.ironflow.v1.ErrorR\x05error\x12)\n" +
	"\x10compensation_for\x18\a \x01(\tR\x0fcompensationFor\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\"|\n" +
	"\x06JobAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rexecution_seq\x18\x03 \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\x04 \x01(\tR\n" +
	"leaseToken\"\x9f\x03\n" +
	"\rEngineMessage\x12?\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x1d.ironflow.v1.WorkerRegisteredH\x00R\n" +
	"registered\x12.\n" +
	"\x03job\x18\x02 \x01(\v2\x1a.ironflow.v1.JobAssignmentH\x00R\x03job\x121\n" +
	"\bstep_ack\x18\x03 \x01(\v2\x14.ironflow.v1.StepAckH\x00R\astepAck\x120\n" +
	"\x06resume\x18\x04 \x01(\v2\x16.ironflow.v1.ResumeJobH\x00R\x06resume\x120\n" +
	"\x06cancel\x18\x05 \x01(\v2\x16.ironflow.v1.CancelJobH\x00R\x06cancel\x123\n" +
	"\bshutdown\x18\x06 \x01(\v2\x15.ironflow.v1.ShutdownH\x00R\bshutdown\x12F\n" +
	"\rlease_refresh\x18\a \x01(\v2\x1f.ironflow.v1.LeaseRefreshResultH\x00R\fleaseRefreshB\t\n" +
	"\apayload\"Q\n" +
	"\x12LeaseRefreshResult\x12;\n" +
	"\bsegments\x18\x01 \x03(\v2\x1f.ironflow.v1.SegmentLeaseStatusR\bsegments\"\x7f\n" +
	"\x12SegmentLeaseStatus\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rexecution_seq\x18\x02 \x01(\x03R\fexecutionSeq\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.ironflow.v1.LeaseStateR\x05state\"c\n" +
	"\x10WorkerRegistered\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x05R\x13heartbeatIntervalMs\"\xc1\x03\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vfunction_id\x18\x03 \x01(\tR\n" +
	"functionId\x12(\n" +
	"\x05event\x18\x04 \x01(\v2\x12.ironflow.v1.EventR\x05event\x12C\n" +
	"\x0fcompleted_steps\x18\x05 \x03(\v2\x1a.ironflow.v1.CompletedStepR\x0ecompletedSteps\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x121\n" +
	"\acontext\x18\b \x01(\v2\x17.ironflow.v1.JobContextR\acontext\x12#\n" +
	"\rexecution_seq\x18\t \x01(\x03R\fexecutionSeq\x12\x1f\n" +
	"\vlease_token\x18\n" +
	" \x01(\tR\n" +
	"leaseToken\x12D\n" +
	"\x10lease_expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"m\n" +
	"\rCompletedStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06output\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06output\"\xa3\x02\n" +
	"\n" +
	"JobContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12A\n" +
	"\bmetadata\x18\x02 \x03(\v2%.ironflow.v1.JobContext.MetadataEntryR\bmetadata\x12>\n" +
	"\asecrets\x18\x03 \x03(\v2$.ironflow.v1.JobContext.SecretsEntryR\asecrets\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\aStepAck\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x96\x01\n" +
	"\tResumeJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x1f\n" +
	"\vresume_type\x18\x03 \x01(\tR\n" +
	"resumeType\x128\n" +
	"\vresume_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"resumeData\":\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"L\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12(\n" +
	"\x10drain_timeout_ms\x18\x02 \x01(\x05R\x0edrainTimeoutMs*t\n" +
	"\n" +
	"LeaseState\x12\x1b\n" +
	"\x17LEASE_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LEASE_STATE_REFRESHED\x10\x01\x12\x15\n" +
	"\x11LEASE_STATE_STALE\x10\x02\x12\x17\n" +
	"\x13LEASE_STATE_UNKNOWN\x10\x032V\n" +
	"\rWorkerService\x12E\n" +
	"\aConnect\x12\x1a.ironflow.v1.WorkerMessage\x1a\x1a.ironflow.v1.EngineMessage(\x010\x01B:Z8github.com/sahina/ironflow-go/api/ironflow/v1;ironflowv1b\x06proto3"

var (
	file_ironflow_v1_worker_proto_rawDescOnce sync.Once
	file_ironflow_v1_worker_proto_rawDescData []byte
)

func file_ironflow_v1_worker_proto_rawDescGZIP() []byte {
	file_ironflow_v1_worker_proto_rawDescOnce.Do(func() {
		file_ironflow_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironflow_v1_worker_proto_rawDesc), len(file_ironflow_v1_worker_proto_rawDesc)))
	})
	return file_ironflow_v1_worker_proto_rawDescData
}

var file_ironflow_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ironflow_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_ironflow_v1_worker_proto_goTypes = []any{
	(LeaseState)(0),               // 0: ironflow.v1.LeaseState
	(*WorkerMessage)(nil),         // 1: ironflow.v1.WorkerMessage
	(*WorkerRegister)(nil),        // 2: ironflow.v1.WorkerRegister
	(*WorkerVersion)(nil),         // 3: ironflow.v1.WorkerVersion
	(*WorkerHeartbeat)(nil),       // 4: ironflow.v1.WorkerHeartbeat
	(*ActiveJob)(nil),             // 5: ironflow.v1.ActiveJob
	(*WorkerMetrics)(nil),         // 6: ironflow.v1.WorkerMetrics
	(*StepStarted)(nil),           // 7: ironflow.v1.StepStarted
	(*StepCompleted)(nil),         // 8: ironflow.v1.StepCompleted
	(*StepFailed)(nil),            // 9: ironflow.v1.StepFailed
	(*StepYielded)(nil),           // 10: ironflow.v1.StepYielded
	(*SleepYield)(nil),            // 11: ironflow.v1.SleepYield
	(*WaitEventYield)(nil),        // 12: ironflow.v1.WaitEventYield
	(*JobCompleted)(nil),          // 13: ironflow.v1.JobCompleted
	(*JobFailed)(nil),             // 14: ironflow.v1.JobFailed
	(*ExecutedStep)(nil),          // 15: ironflow.v1.ExecutedStep
	(*JobAck)(nil),                // 16: ironflow.v1.JobAck
	(*EngineMessage)(nil),         // 17: ironflow.v1.EngineMessage
	(*LeaseRefreshResult)(nil),    // 18: ironflow.v1.LeaseRefreshResult
	(*SegmentLeaseStatus)(nil),    // 19: ironflow.v1.SegmentLeaseStatus
	(*WorkerRegistered)(nil),      // 20: ironflow.v1.WorkerRegistered
	(*JobAssignment)(nil),         // 21: ironflow.v1.JobAssignment
	(*CompletedStep)(nil),         // 22: ironflow.v1.CompletedStep
	(*JobContext)(nil),            // 23: ironflow.v1.JobContext
	(*StepAck)(nil),               // 24: ironflow.v1.StepAck
	(*ResumeJob)(nil),             // 25: ironflow.v1.ResumeJob
	(*CancelJob)(nil),             // 26: ironflow.v1.CancelJob
	(*Shutdown)(nil),              // 27: ironflow.v1.Shutdown
	nil,                           // 28: ironflow.v1.WorkerRegister.LabelsEntry
	nil,                           // 29: ironflow.v1.JobContext.MetadataEntry
	nil,                           // 30: ironflow.v1.JobContext.SecretsEntry
	(*timestamppb.Timestamp)(nil), // 31: google.protobuf.Timestamp
	(StepType)(0),                 // 32: ironflow.v1.StepType
	(*structpb.Struct)(nil),       // 33: google.protobuf.Struct
	(*Error)(nil),                 // 34: ironflow.v1.Error
	(*Event)(nil),                 // 35: ironflow.v1.Event
}
var file_ironflow_v1_worker_proto_depIdxs = []int32{
	2,  // 0: ironflow.v1.WorkerMessage.register:type_name -> ironflow.v1.WorkerRegister
	4,  // 1: ironflow.v1.WorkerMessage.heartbeat:type_name -> ironflow.v1.WorkerHeartbeat
	7,  // 2: ironflow.v1.WorkerMessage.step_started:type_name -> ironflow.v1.StepStarted
	8,  // 3: ironflow.v1.WorkerMessage.step_completed:type_name -> ironflow.v1.StepCompleted
	9,  // 4: ironflow.v1.WorkerMessage.step_failed:type_name -> ironflow.v1.StepFailed
	10, // 5: ironflow.v1.WorkerMessage.step_yielded:type_name -> ironflow.v1.StepYielded
	13, // 6: ironflow.v1.WorkerMessage.job_completed:type_name -> ironflow.v1.JobCompleted
	14, // 7: ironflow.v1.WorkerMessage.job_failed:type_name -> ironflow.v1.JobFailed
	16, // 8: ironflow.v1.WorkerMessage.job_ack:type_name -> ironflow.v1.JobAck
	28, // 9: ironflow.v1.WorkerRegister.labels:type_name -> ironflow.v1.WorkerRegister.LabelsEntry
	3,  // 10: ironflow.v1.WorkerRegister.version:type_name -> ironflow.v1.WorkerVersion
	5,  // 11: ironflow.v1.WorkerHeartbeat.jobs:type_name -> ironflow.v1.ActiveJob
	6,  // 12: ironflow.v1.WorkerHeartbeat.metrics:type_name -> ironflow.v1.WorkerMetrics
	31, // 13: ironflow.v1.ActiveJob.started_at:type_name -> google.protobuf.Timestamp
	32, // 14: ironflow.v1.StepStarted.step_type:type_name -> ironflow.v1.StepType
	33, // 15: ironflow.v1.StepCompleted.output:type_name -> google.protobuf.Struct
	34, // 16: ironflow.v1.StepFailed.error:type_name -> ironflow.v1.Error
	11, // 17: ironflow.v1.StepYielded.sleep:type_name -> ironflow.v1.SleepYield
	12, // 18: ironflow.v1.StepYielded.wait_event:type_name -> ironflow.v1.WaitEventYield
	31, // 19: ironflow.v1.SleepYield.until:type_name -> google.protobuf.Timestamp
	31, // 20: ironflow.v1.WaitEventYield.timeout:type_name -> google.protobuf.Timestamp
	33, // 21: ironflow.v1.JobCompleted.output:type_name -> google.protobuf.Struct
	34, // 22: ironflow.v1.JobFailed.error:type_name -> ironflow.v1.Error
	15, // 23: ironflow.v1.JobFailed.steps:type_name -> ironflow.v1.ExecutedStep
	33, // 24: ironflow.v1.ExecutedStep.output:type_name -> google.protobuf.Struct
	34, // 25: ironflow.v1.ExecutedStep.error:type_name -> ironflow.v1.Error
	20, // 26: ironflow.v1.EngineMessage.registered:type_name -> ironflow.v1.WorkerRegistered
	21, // 27: ironflow.v1.EngineMessage.job:type_name -> ironflow.v1.JobAssignment
	24, // 28: ironflow.v1.EngineMessage.step_ack:type_name -> ironflow.v1.StepAck
	25, // 29: ironflow.v1.EngineMessage.resume:type_name -> ironflow.v1.ResumeJob
	26, // 30: ironflow.v1.EngineMessage.cancel:type_name -> ironflow.v1.CancelJob
	27, // 31: ironflow.v1.EngineMessage.shutdown:type_name -> ironflow.v1.Shutdown
	18, // 32: ironflow.v1.EngineMessage.lease_refresh:type_name -> ironflow.v1.LeaseRefreshResult
	19, // 33: ironflow.v1.LeaseRefreshResult.segments:type_name -> ironflow.v1.SegmentLeaseStatus
	0,  // 34: ironflow.v1.SegmentLeaseStatus.state:type_name -> ironflow.v1.LeaseState
	35, // 35: ironflow.v1.JobAssignment.event:type_name -> ironflow.v1.Event
	22, // 36: ironflow.v1.JobAssignment.completed_steps:type_name -> ironflow.v1.CompletedStep
	23, // 37: ironflow.v1.JobAssignment.context:type_name -> ironflow.v1.JobContext
	31, // 38: ironflow.v1.JobAssignment.lease_expires_at:type_name -> google.protobuf.Timestamp
	33, // 39: ironflow.v1.CompletedStep.output:type_name -> google.protobuf.Struct
	29, // 40: ironflow.v1.JobContext.metadata:type_name -> ironflow.v1.JobContext.MetadataEntry
	30, // 41: ironflow.v1.JobContext.secrets:type_name -> ironflow.v1.JobContext.SecretsEntry
	33, // 42: ironflow.v1.ResumeJob.resume_data:type_name -> google.protobuf.Struct
	1,  // 43: ironflow.v1.WorkerService.Connect:input_type -> ironflow.v1.WorkerMessage
	17, // 44: ironflow.v1.WorkerService.Connect:output_type -> ironflow.v1.EngineMessage
	44, // [44:45] is the sub-list for method output_type
	43, // [43:44] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_ironflow_v1_worker_proto_init() }
func file_ironflow_v1_worker_proto_init() {
	if File_ironflow_v1_worker_proto != nil {
		return
	}
	file_ironflow_v1_types_proto_init()
	file_ironflow_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_StepStarted)(nil),
		(*WorkerMessage_StepCompleted)(nil),
		(*WorkerMessage_StepFailed)(nil),
		(*WorkerMessage_StepYielded)(nil),
		(*WorkerMessage_JobCompleted)(nil),
		(*WorkerMessage_JobFailed)(nil),
		(*WorkerMessage_JobAck)(nil),
	}
	file_ironflow_v1_worker_proto_msgTypes[9].OneofWrappers = []any{
		(*StepYielded_Sleep)(nil),
		(*StepYielded_WaitEvent)(nil),
	}
	file_ironflow_v1_worker_proto_msgTypes[16].OneofWrappers = []any{
		(*EngineMessage_Registered)(nil),
		(*EngineMessage_Job)(nil),
		(*EngineMessage_StepAck)(nil),
		(*EngineMessage_Resume)(nil),
		(*EngineMessage_Cancel)(nil),
		(*EngineMessage_Shutdown)(nil),
		(*EngineMessage_LeaseRefresh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironflow_v1_worker_proto_rawDesc), len(file_ironflow_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironflow_v1_worker_proto_goTypes,
		DependencyIndexes: file_ironflow_v1_worker_proto_depIdxs,
		EnumInfos:         file_ironflow_v1_worker_proto_enumTypes,
		MessageInfos:      file_ironflow_v1_worker_proto_msgTypes,
	}.Build()
	File_ironflow_v1_worker_proto = out.File
	file_ironflow_v1_worker_proto_goTypes = nil
	file_ironflow_v1_worker_proto_depIdxs = nil
}
