// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ironflow/v1/environment.proto

package ironflowv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sahina/ironflow-go/api/ironflow/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EnvironmentServiceName is the fully-qualified name of the EnvironmentService service.
	EnvironmentServiceName = "ironflow.v1.EnvironmentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EnvironmentServiceCreateEnvironmentProcedure is the fully-qualified name of the
	// EnvironmentService's CreateEnvironment RPC.
	EnvironmentServiceCreateEnvironmentProcedure = "/ironflow.v1.EnvironmentService/CreateEnvironment"
	// EnvironmentServiceGetEnvironmentProcedure is the fully-qualified name of the EnvironmentService's
	// GetEnvironment RPC.
	EnvironmentServiceGetEnvironmentProcedure = "/ironflow.v1.EnvironmentService/GetEnvironment"
	// EnvironmentServiceListEnvironmentsProcedure is the fully-qualified name of the
	// EnvironmentService's ListEnvironments RPC.
	EnvironmentServiceListEnvironmentsProcedure = "/ironflow.v1.EnvironmentService/ListEnvironments"
	// EnvironmentServiceDeleteEnvironmentProcedure is the fully-qualified name of the
	// EnvironmentService's DeleteEnvironment RPC.
	EnvironmentServiceDeleteEnvironmentProcedure = "/ironflow.v1.EnvironmentService/DeleteEnvironment"
	// EnvironmentServiceRotateAPIKeyProcedure is the fully-qualified name of the EnvironmentService's
	// RotateAPIKey RPC.
	EnvironmentServiceRotateAPIKeyProcedure = "/ironflow.v1.EnvironmentService/RotateAPIKey"
)

// EnvironmentServiceClient is a client for the ironflow.v1.EnvironmentService service.
type EnvironmentServiceClient interface {
	CreateEnvironment(context.Context, *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error)
	GetEnvironment(context.Context, *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error)
	ListEnvironments(context.Context, *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error)
	DeleteEnvironment(context.Context, *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error)
	RotateAPIKey(context.Context, *connect.Request[v1.RotateAPIKeyRequest]) (*connect.Response[v1.RotateAPIKeyResponse], error)
}

// NewEnvironmentServiceClient constructs a client for the ironflow.v1.EnvironmentService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEnvironmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EnvironmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	environmentServiceMethods := v1.File_ironflow_v1_environment_proto.Services().ByName("EnvironmentService").Methods()
	return &environmentServiceClient{
		createEnvironment: connect.NewClient[v1.CreateEnvironmentRequest, v1.EnvironmentInfo](
			httpClient,
			baseURL+EnvironmentServiceCreateEnvironmentProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("CreateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		getEnvironment: connect.NewClient[v1.GetEnvironmentRequest, v1.EnvironmentInfo](
			httpClient,
			baseURL+EnvironmentServiceGetEnvironmentProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("GetEnvironment")),
			connect.WithClientOptions(opts...),
		),
		listEnvironments: connect.NewClient[v1.ListEnvironmentsRequest, v1.ListEnvironmentsResponse](
			httpClient,
			baseURL+EnvironmentServiceListEnvironmentsProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("ListEnvironments")),
			connect.WithClientOptions(opts...),
		),
		deleteEnvironment: connect.NewClient[v1.DeleteEnvironmentRequest, v1.DeleteEnvironmentResponse](
			httpClient,
			baseURL+EnvironmentServiceDeleteEnvironmentProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("DeleteEnvironment")),
			connect.WithClientOptions(opts...),
		),
		rotateAPIKey: connect.NewClient[v1.RotateAPIKeyRequest, v1.RotateAPIKeyResponse](
			httpClient,
			baseURL+EnvironmentServiceRotateAPIKeyProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("RotateAPIKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// environmentServiceClient implements EnvironmentServiceClient.
type environmentServiceClient struct {
	createEnvironment *connect.Client[v1.CreateEnvironmentRequest, v1.EnvironmentInfo]
	getEnvironment    *connect.Client[v1.GetEnvironmentRequest, v1.EnvironmentInfo]
	listEnvironments  *connect.Client[v1.ListEnvironmentsRequest, v1.ListEnvironmentsResponse]
	deleteEnvironment *connect.Client[v1.DeleteEnvironmentRequest, v1.DeleteEnvironmentResponse]
	rotateAPIKey      *connect.Client[v1.RotateAPIKeyRequest, v1.RotateAPIKeyResponse]
}

// CreateEnvironment calls ironflow.v1.EnvironmentService.CreateEnvironment.
func (c *environmentServiceClient) CreateEnvironment(ctx context.Context, req *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error) {
	return c.createEnvironment.CallUnary(ctx, req)
}

// GetEnvironment calls ironflow.v1.EnvironmentService.GetEnvironment.
func (c *environmentServiceClient) GetEnvironment(ctx context.Context, req *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error) {
	return c.getEnvironment.CallUnary(ctx, req)
}

// ListEnvironments calls ironflow.v1.EnvironmentService.ListEnvironments.
func (c *environmentServiceClient) ListEnvironments(ctx context.Context, req *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error) {
	return c.listEnvironments.CallUnary(ctx, req)
}

// DeleteEnvironment calls ironflow.v1.EnvironmentService.DeleteEnvironment.
func (c *environmentServiceClient) DeleteEnvironment(ctx context.Context, req *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error) {
	return c.deleteEnvironment.CallUnary(ctx, req)
}

// RotateAPIKey calls ironflow.v1.EnvironmentService.RotateAPIKey.
func (c *environmentServiceClient) RotateAPIKey(ctx context.Context, req *connect.Request[v1.RotateAPIKeyRequest]) (*connect.Response[v1.RotateAPIKeyResponse], error) {
	return c.rotateAPIKey.CallUnary(ctx, req)
}

// EnvironmentServiceHandler is an implementation of the ironflow.v1.EnvironmentService service.
type EnvironmentServiceHandler interface {
	CreateEnvironment(context.Context, *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error)
	GetEnvironment(context.Context, *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error)
	ListEnvironments(context.Context, *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error)
	DeleteEnvironment(context.Context, *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error)
	RotateAPIKey(context.Context, *connect.Request[v1.RotateAPIKeyRequest]) (*connect.Response[v1.RotateAPIKeyResponse], error)
}

// NewEnvironmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEnvironmentServiceHandler(svc EnvironmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	environmentServiceMethods := v1.File_ironflow_v1_environment_proto.Services().ByName("EnvironmentService").Methods()
	environmentServiceCreateEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentServiceCreateEnvironmentProcedure,
		svc.CreateEnvironment,
		connect.WithSchema(environmentServiceMethods.ByName("CreateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	environmentServiceGetEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentServiceGetEnvironmentProcedure,
		svc.GetEnvironment,
		connect.WithSchema(environmentServiceMethods.ByName("GetEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	environmentServiceListEnvironmentsHandler := connect.NewUnaryHandler(
		EnvironmentServiceListEnvironmentsProcedure,
		svc.ListEnvironments,
		connect.WithSchema(environmentServiceMethods.ByName("ListEnvironments")),
		connect.WithHandlerOptions(opts...),
	)
	environmentServiceDeleteEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentServiceDeleteEnvironmentProcedure,
		svc.DeleteEnvironment,
		connect.WithSchema(environmentServiceMethods.ByName("DeleteEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	environmentServiceRotateAPIKeyHandler := connect.NewUnaryHandler(
		EnvironmentServiceRotateAPIKeyProcedure,
		svc.RotateAPIKey,
		connect.WithSchema(environmentServiceMethods.ByName("RotateAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ironflow.v1.EnvironmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EnvironmentServiceCreateEnvironmentProcedure:
			environmentServiceCreateEnvironmentHandler.ServeHTTP(w, r)
		case EnvironmentServiceGetEnvironmentProcedure:
			environmentServiceGetEnvironmentHandler.ServeHTTP(w, r)
		case EnvironmentServiceListEnvironmentsProcedure:
			environmentServiceListEnvironmentsHandler.ServeHTTP(w, r)
		case EnvironmentServiceDeleteEnvironmentProcedure:
			environmentServiceDeleteEnvironmentHandler.ServeHTTP(w, r)
		case EnvironmentServiceRotateAPIKeyProcedure:
			environmentServiceRotateAPIKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEnvironmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEnvironmentServiceHandler struct{}

func (UnimplementedEnvironmentServiceHandler) CreateEnvironment(context.Context, *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.EnvironmentService.CreateEnvironment is not implemented"))
}

func (UnimplementedEnvironmentServiceHandler) GetEnvironment(context.Context, *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.EnvironmentInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.EnvironmentService.GetEnvironment is not implemented"))
}

func (UnimplementedEnvironmentServiceHandler) ListEnvironments(context.Context, *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.EnvironmentService.ListEnvironments is not implemented"))
}

func (UnimplementedEnvironmentServiceHandler) DeleteEnvironment(context.Context, *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.EnvironmentService.DeleteEnvironment is not implemented"))
}

func (UnimplementedEnvironmentServiceHandler) RotateAPIKey(context.Context, *connect.Request[v1.RotateAPIKeyRequest]) (*connect.Response[v1.RotateAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.EnvironmentService.RotateAPIKey is not implemented"))
}
