// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ironflow/v1/ironflow.proto

package ironflowv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sahina/ironflow-go/api/ironflow/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IronflowServiceName is the fully-qualified name of the IronflowService service.
	IronflowServiceName = "ironflow.v1.IronflowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IronflowServiceRegisterFunctionProcedure is the fully-qualified name of the IronflowService's
	// RegisterFunction RPC.
	IronflowServiceRegisterFunctionProcedure = "/ironflow.v1.IronflowService/RegisterFunction"
	// IronflowServiceGetFunctionProcedure is the fully-qualified name of the IronflowService's
	// GetFunction RPC.
	IronflowServiceGetFunctionProcedure = "/ironflow.v1.IronflowService/GetFunction"
	// IronflowServiceListFunctionsProcedure is the fully-qualified name of the IronflowService's
	// ListFunctions RPC.
	IronflowServiceListFunctionsProcedure = "/ironflow.v1.IronflowService/ListFunctions"
	// IronflowServiceUpdateFunctionStatusProcedure is the fully-qualified name of the IronflowService's
	// UpdateFunctionStatus RPC.
	IronflowServiceUpdateFunctionStatusProcedure = "/ironflow.v1.IronflowService/UpdateFunctionStatus"
	// IronflowServiceDeleteFunctionProcedure is the fully-qualified name of the IronflowService's
	// DeleteFunction RPC.
	IronflowServiceDeleteFunctionProcedure = "/ironflow.v1.IronflowService/DeleteFunction"
	// IronflowServiceListFunctionHistoryProcedure is the fully-qualified name of the IronflowService's
	// ListFunctionHistory RPC.
	IronflowServiceListFunctionHistoryProcedure = "/ironflow.v1.IronflowService/ListFunctionHistory"
	// IronflowServiceGetFunctionAtVersionProcedure is the fully-qualified name of the IronflowService's
	// GetFunctionAtVersion RPC.
	IronflowServiceGetFunctionAtVersionProcedure = "/ironflow.v1.IronflowService/GetFunctionAtVersion"
	// IronflowServiceRollbackFunctionProcedure is the fully-qualified name of the IronflowService's
	// RollbackFunction RPC.
	IronflowServiceRollbackFunctionProcedure = "/ironflow.v1.IronflowService/RollbackFunction"
	// IronflowServiceTriggerProcedure is the fully-qualified name of the IronflowService's Trigger RPC.
	IronflowServiceTriggerProcedure = "/ironflow.v1.IronflowService/Trigger"
	// IronflowServiceEmitProcedure is the fully-qualified name of the IronflowService's Emit RPC.
	IronflowServiceEmitProcedure = "/ironflow.v1.IronflowService/Emit"
	// IronflowServiceTriggerSyncProcedure is the fully-qualified name of the IronflowService's
	// TriggerSync RPC.
	IronflowServiceTriggerSyncProcedure = "/ironflow.v1.IronflowService/TriggerSync"
	// IronflowServiceTriggerBatchProcedure is the fully-qualified name of the IronflowService's
	// TriggerBatch RPC.
	IronflowServiceTriggerBatchProcedure = "/ironflow.v1.IronflowService/TriggerBatch"
	// IronflowServiceGetRunProcedure is the fully-qualified name of the IronflowService's GetRun RPC.
	IronflowServiceGetRunProcedure = "/ironflow.v1.IronflowService/GetRun"
	// IronflowServiceListRunsProcedure is the fully-qualified name of the IronflowService's ListRuns
	// RPC.
	IronflowServiceListRunsProcedure = "/ironflow.v1.IronflowService/ListRuns"
	// IronflowServiceGetRunStepsProcedure is the fully-qualified name of the IronflowService's
	// GetRunSteps RPC.
	IronflowServiceGetRunStepsProcedure = "/ironflow.v1.IronflowService/GetRunSteps"
	// IronflowServiceCancelRunProcedure is the fully-qualified name of the IronflowService's CancelRun
	// RPC.
	IronflowServiceCancelRunProcedure = "/ironflow.v1.IronflowService/CancelRun"
	// IronflowServicePatchStepProcedure is the fully-qualified name of the IronflowService's PatchStep
	// RPC.
	IronflowServicePatchStepProcedure = "/ironflow.v1.IronflowService/PatchStep"
	// IronflowServiceResumeRunProcedure is the fully-qualified name of the IronflowService's ResumeRun
	// RPC.
	IronflowServiceResumeRunProcedure = "/ironflow.v1.IronflowService/ResumeRun"
	// IronflowServicePauseRunProcedure is the fully-qualified name of the IronflowService's PauseRun
	// RPC.
	IronflowServicePauseRunProcedure = "/ironflow.v1.IronflowService/PauseRun"
	// IronflowServiceGetPausedStateProcedure is the fully-qualified name of the IronflowService's
	// GetPausedState RPC.
	IronflowServiceGetPausedStateProcedure = "/ironflow.v1.IronflowService/GetPausedState"
	// IronflowServiceInjectStepOutputProcedure is the fully-qualified name of the IronflowService's
	// InjectStepOutput RPC.
	IronflowServiceInjectStepOutputProcedure = "/ironflow.v1.IronflowService/InjectStepOutput"
	// IronflowServiceHealthProcedure is the fully-qualified name of the IronflowService's Health RPC.
	IronflowServiceHealthProcedure = "/ironflow.v1.IronflowService/Health"
	// IronflowServiceInfoProcedure is the fully-qualified name of the IronflowService's Info RPC.
	IronflowServiceInfoProcedure = "/ironflow.v1.IronflowService/Info"
)

// IronflowServiceClient is a client for the ironflow.v1.IronflowService service.
type IronflowServiceClient interface {
	// Register or update a function definition
	RegisterFunction(context.Context, *connect.Request[v1.RegisterFunctionRequest]) (*connect.Response[v1.RegisterFunctionResponse], error)
	// Get a function by ID
	GetFunction(context.Context, *connect.Request[v1.GetFunctionRequest]) (*connect.Response[v1.Function], error)
	// List all registered functions
	ListFunctions(context.Context, *connect.Request[v1.ListFunctionsRequest]) (*connect.Response[v1.ListFunctionsResponse], error)
	// Update function status (pause, activate, archive)
	UpdateFunctionStatus(context.Context, *connect.Request[v1.UpdateFunctionStatusRequest]) (*connect.Response[v1.Function], error)
	// Delete a function
	DeleteFunction(context.Context, *connect.Request[v1.DeleteFunctionRequest]) (*connect.Response[emptypb.Empty], error)
	// List function configuration history
	ListFunctionHistory(context.Context, *connect.Request[v1.ListFunctionHistoryRequest]) (*connect.Response[v1.ListFunctionHistoryResponse], error)
	// Get function configuration at a specific version
	GetFunctionAtVersion(context.Context, *connect.Request[v1.GetFunctionAtVersionRequest]) (*connect.Response[v1.GetFunctionAtVersionResponse], error)
	// Roll back a function to a previous version
	RollbackFunction(context.Context, *connect.Request[v1.RollbackFunctionRequest]) (*connect.Response[v1.RollbackFunctionResponse], error)
	// Trigger an event (async by default)
	Trigger(context.Context, *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error)
	// Emit an event (alias for Trigger with emit semantics)
	Emit(context.Context, *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error)
	// Trigger and wait for completion (sync)
	TriggerSync(context.Context, *connect.Request[v1.TriggerSyncRequest]) (*connect.Response[v1.TriggerSyncResponse], error)
	// Batch trigger multiple events
	TriggerBatch(context.Context, *connect.Request[v1.TriggerBatchRequest]) (*connect.Response[v1.TriggerBatchResponse], error)
	// Get a run by ID
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error)
	// List runs with filtering
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	// Get steps for a run
	GetRunSteps(context.Context, *connect.Request[v1.GetRunStepsRequest]) (*connect.Response[v1.GetRunStepsResponse], error)
	// Cancel a running workflow
	CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.Run], error)
	// Patch a step's output
	PatchStep(context.Context, *connect.Request[v1.PatchStepRequest]) (*connect.Response[v1.Step], error)
	// Resume a paused/failed run
	ResumeRun(context.Context, *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.Run], error)
	// Request a running workflow to pause at the next step boundary
	PauseRun(context.Context, *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error)
	// Get the paused state of a run including completed steps
	GetPausedState(context.Context, *connect.Request[v1.GetPausedStateRequest]) (*connect.Response[v1.GetPausedStateResponse], error)
	// Inject a modified output for a completed step
	InjectStepOutput(context.Context, *connect.Request[v1.InjectStepOutputRequest]) (*connect.Response[v1.InjectStepOutputResponse], error)
	// Health check
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
	// Server info
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
}

// NewIronflowServiceClient constructs a client for the ironflow.v1.IronflowService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIronflowServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IronflowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ironflowServiceMethods := v1.File_ironflow_v1_ironflow_proto.Services().ByName("IronflowService").Methods()
	return &ironflowServiceClient{
		registerFunction: connect.NewClient[v1.RegisterFunctionRequest, v1.RegisterFunctionResponse](
			httpClient,
			baseURL+IronflowServiceRegisterFunctionProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("RegisterFunction")),
			connect.WithClientOptions(opts...),
		),
		getFunction: connect.NewClient[v1.GetFunctionRequest, v1.Function](
			httpClient,
			baseURL+IronflowServiceGetFunctionProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("GetFunction")),
			connect.WithClientOptions(opts...),
		),
		listFunctions: connect.NewClient[v1.ListFunctionsRequest, v1.ListFunctionsResponse](
			httpClient,
			baseURL+IronflowServiceListFunctionsProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("ListFunctions")),
			connect.WithClientOptions(opts...),
		),
		updateFunctionStatus: connect.NewClient[v1.UpdateFunctionStatusRequest, v1.Function](
			httpClient,
			baseURL+IronflowServiceUpdateFunctionStatusProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("UpdateFunctionStatus")),
			connect.WithClientOptions(opts...),
		),
		deleteFunction: connect.NewClient[v1.DeleteFunctionRequest, emptypb.Empty](
			httpClient,
			baseURL+IronflowServiceDeleteFunctionProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("DeleteFunction")),
			connect.WithClientOptions(opts...),
		),
		listFunctionHistory: connect.NewClient[v1.ListFunctionHistoryRequest, v1.ListFunctionHistoryResponse](
			httpClient,
			baseURL+IronflowServiceListFunctionHistoryProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("ListFunctionHistory")),
			connect.WithClientOptions(opts...),
		),
		getFunctionAtVersion: connect.NewClient[v1.GetFunctionAtVersionRequest, v1.GetFunctionAtVersionResponse](
			httpClient,
			baseURL+IronflowServiceGetFunctionAtVersionProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("GetFunctionAtVersion")),
			connect.WithClientOptions(opts...),
		),
		rollbackFunction: connect.NewClient[v1.RollbackFunctionRequest, v1.RollbackFunctionResponse](
			httpClient,
			baseURL+IronflowServiceRollbackFunctionProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("RollbackFunction")),
			connect.WithClientOptions(opts...),
		),
		trigger: connect.NewClient[v1.TriggerRequest, v1.TriggerResponse](
			httpClient,
			baseURL+IronflowServiceTriggerProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("Trigger")),
			connect.WithClientOptions(opts...),
		),
		emit: connect.NewClient[v1.TriggerRequest, v1.TriggerResponse](
			httpClient,
			baseURL+IronflowServiceEmitProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("Emit")),
			connect.WithClientOptions(opts...),
		),
		triggerSync: connect.NewClient[v1.TriggerSyncRequest, v1.TriggerSyncResponse](
			httpClient,
			baseURL+IronflowServiceTriggerSyncProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("TriggerSync")),
			connect.WithClientOptions(opts...),
		),
		triggerBatch: connect.NewClient[v1.TriggerBatchRequest, v1.TriggerBatchResponse](
			httpClient,
			baseURL+IronflowServiceTriggerBatchProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("TriggerBatch")),
			connect.WithClientOptions(opts...),
		),
		getRun: connect.NewClient[v1.GetRunRequest, v1.Run](
			httpClient,
			baseURL+IronflowServiceGetRunProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("GetRun")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[v1.ListRunsRequest, v1.ListRunsResponse](
			httpClient,
			baseURL+IronflowServiceListRunsProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		getRunSteps: connect.NewClient[v1.GetRunStepsRequest, v1.GetRunStepsResponse](
			httpClient,
			baseURL+IronflowServiceGetRunStepsProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("GetRunSteps")),
			connect.WithClientOptions(opts...),
		),
		cancelRun: connect.NewClient[v1.CancelRunRequest, v1.Run](
			httpClient,
			baseURL+IronflowServiceCancelRunProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("CancelRun")),
			connect.WithClientOptions(opts...),
		),
		patchStep: connect.NewClient[v1.PatchStepRequest, v1.Step](
			httpClient,
			baseURL+IronflowServicePatchStepProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("PatchStep")),
			connect.WithClientOptions(opts...),
		),
		resumeRun: connect.NewClient[v1.ResumeRunRequest, v1.Run](
			httpClient,
			baseURL+IronflowServiceResumeRunProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("ResumeRun")),
			connect.WithClientOptions(opts...),
		),
		pauseRun: connect.NewClient[v1.PauseRunRequest, v1.PauseRunResponse](
			httpClient,
			baseURL+IronflowServicePauseRunProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("PauseRun")),
			connect.WithClientOptions(opts...),
		),
		getPausedState: connect.NewClient[v1.GetPausedStateRequest, v1.GetPausedStateResponse](
			httpClient,
			baseURL+IronflowServiceGetPausedStateProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("GetPausedState")),
			connect.WithClientOptions(opts...),
		),
		injectStepOutput: connect.NewClient[v1.InjectStepOutputRequest, v1.InjectStepOutputResponse](
			httpClient,
			baseURL+IronflowServiceInjectStepOutputProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("InjectStepOutput")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+IronflowServiceHealthProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+IronflowServiceInfoProcedure,
			connect.WithSchema(ironflowServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ironflowServiceClient implements IronflowServiceClient.
type ironflowServiceClient struct {
	registerFunction     *connect.Client[v1.RegisterFunctionRequest, v1.RegisterFunctionResponse]
	getFunction          *connect.Client[v1.GetFunctionRequest, v1.Function]
	listFunctions        *connect.Client[v1.ListFunctionsRequest, v1.ListFunctionsResponse]
	updateFunctionStatus *connect.Client[v1.UpdateFunctionStatusRequest, v1.Function]
	deleteFunction       *connect.Client[v1.DeleteFunctionRequest, emptypb.Empty]
	listFunctionHistory  *connect.Client[v1.ListFunctionHistoryRequest, v1.ListFunctionHistoryResponse]
	getFunctionAtVersion *connect.Client[v1.GetFunctionAtVersionRequest, v1.GetFunctionAtVersionResponse]
	rollbackFunction     *connect.Client[v1.RollbackFunctionRequest, v1.RollbackFunctionResponse]
	trigger              *connect.Client[v1.TriggerRequest, v1.TriggerResponse]
	emit                 *connect.Client[v1.TriggerRequest, v1.TriggerResponse]
	triggerSync          *connect.Client[v1.TriggerSyncRequest, v1.TriggerSyncResponse]
	triggerBatch         *connect.Client[v1.TriggerBatchRequest, v1.TriggerBatchResponse]
	getRun               *connect.Client[v1.GetRunRequest, v1.Run]
	listRuns             *connect.Client[v1.ListRunsRequest, v1.ListRunsResponse]
	getRunSteps          *connect.Client[v1.GetRunStepsRequest, v1.GetRunStepsResponse]
	cancelRun            *connect.Client[v1.CancelRunRequest, v1.Run]
	patchStep            *connect.Client[v1.PatchStepRequest, v1.Step]
	resumeRun            *connect.Client[v1.ResumeRunRequest, v1.Run]
	pauseRun             *connect.Client[v1.PauseRunRequest, v1.PauseRunResponse]
	getPausedState       *connect.Client[v1.GetPausedStateRequest, v1.GetPausedStateResponse]
	injectStepOutput     *connect.Client[v1.InjectStepOutputRequest, v1.InjectStepOutputResponse]
	health               *connect.Client[v1.HealthRequest, v1.HealthResponse]
	info                 *connect.Client[v1.InfoRequest, v1.InfoResponse]
}

// RegisterFunction calls ironflow.v1.IronflowService.RegisterFunction.
func (c *ironflowServiceClient) RegisterFunction(ctx context.Context, req *connect.Request[v1.RegisterFunctionRequest]) (*connect.Response[v1.RegisterFunctionResponse], error) {
	return c.registerFunction.CallUnary(ctx, req)
}

// GetFunction calls ironflow.v1.IronflowService.GetFunction.
func (c *ironflowServiceClient) GetFunction(ctx context.Context, req *connect.Request[v1.GetFunctionRequest]) (*connect.Response[v1.Function], error) {
	return c.getFunction.CallUnary(ctx, req)
}

// ListFunctions calls ironflow.v1.IronflowService.ListFunctions.
func (c *ironflowServiceClient) ListFunctions(ctx context.Context, req *connect.Request[v1.ListFunctionsRequest]) (*connect.Response[v1.ListFunctionsResponse], error) {
	return c.listFunctions.CallUnary(ctx, req)
}

// UpdateFunctionStatus calls ironflow.v1.IronflowService.UpdateFunctionStatus.
func (c *ironflowServiceClient) UpdateFunctionStatus(ctx context.Context, req *connect.Request[v1.UpdateFunctionStatusRequest]) (*connect.Response[v1.Function], error) {
	return c.updateFunctionStatus.CallUnary(ctx, req)
}

// DeleteFunction calls ironflow.v1.IronflowService.DeleteFunction.
func (c *ironflowServiceClient) DeleteFunction(ctx context.Context, req *connect.Request[v1.DeleteFunctionRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteFunction.CallUnary(ctx, req)
}

// ListFunctionHistory calls ironflow.v1.IronflowService.ListFunctionHistory.
func (c *ironflowServiceClient) ListFunctionHistory(ctx context.Context, req *connect.Request[v1.ListFunctionHistoryRequest]) (*connect.Response[v1.ListFunctionHistoryResponse], error) {
	return c.listFunctionHistory.CallUnary(ctx, req)
}

// GetFunctionAtVersion calls ironflow.v1.IronflowService.GetFunctionAtVersion.
func (c *ironflowServiceClient) GetFunctionAtVersion(ctx context.Context, req *connect.Request[v1.GetFunctionAtVersionRequest]) (*connect.Response[v1.GetFunctionAtVersionResponse], error) {
	return c.getFunctionAtVersion.CallUnary(ctx, req)
}

// RollbackFunction calls ironflow.v1.IronflowService.RollbackFunction.
func (c *ironflowServiceClient) RollbackFunction(ctx context.Context, req *connect.Request[v1.RollbackFunctionRequest]) (*connect.Response[v1.RollbackFunctionResponse], error) {
	return c.rollbackFunction.CallUnary(ctx, req)
}

// Trigger calls ironflow.v1.IronflowService.Trigger.
func (c *ironflowServiceClient) Trigger(ctx context.Context, req *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error) {
	return c.trigger.CallUnary(ctx, req)
}

// Emit calls ironflow.v1.IronflowService.Emit.
func (c *ironflowServiceClient) Emit(ctx context.Context, req *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error) {
	return c.emit.CallUnary(ctx, req)
}

// TriggerSync calls ironflow.v1.IronflowService.TriggerSync.
func (c *ironflowServiceClient) TriggerSync(ctx context.Context, req *connect.Request[v1.TriggerSyncRequest]) (*connect.Response[v1.TriggerSyncResponse], error) {
	return c.triggerSync.CallUnary(ctx, req)
}

// TriggerBatch calls ironflow.v1.IronflowService.TriggerBatch.
func (c *ironflowServiceClient) TriggerBatch(ctx context.Context, req *connect.Request[v1.TriggerBatchRequest]) (*connect.Response[v1.TriggerBatchResponse], error) {
	return c.triggerBatch.CallUnary(ctx, req)
}

// GetRun calls ironflow.v1.IronflowService.GetRun.
func (c *ironflowServiceClient) GetRun(ctx context.Context, req *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error) {
	return c.getRun.CallUnary(ctx, req)
}

// ListRuns calls ironflow.v1.IronflowService.ListRuns.
func (c *ironflowServiceClient) ListRuns(ctx context.Context, req *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// GetRunSteps calls ironflow.v1.IronflowService.GetRunSteps.
func (c *ironflowServiceClient) GetRunSteps(ctx context.Context, req *connect.Request[v1.GetRunStepsRequest]) (*connect.Response[v1.GetRunStepsResponse], error) {
	return c.getRunSteps.CallUnary(ctx, req)
}

// CancelRun calls ironflow.v1.IronflowService.CancelRun.
func (c *ironflowServiceClient) CancelRun(ctx context.Context, req *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.Run], error) {
	return c.cancelRun.CallUnary(ctx, req)
}

// PatchStep calls ironflow.v1.IronflowService.PatchStep.
func (c *ironflowServiceClient) PatchStep(ctx context.Context, req *connect.Request[v1.PatchStepRequest]) (*connect.Response[v1.Step], error) {
	return c.patchStep.CallUnary(ctx, req)
}

// ResumeRun calls ironflow.v1.IronflowService.ResumeRun.
func (c *ironflowServiceClient) ResumeRun(ctx context.Context, req *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.Run], error) {
	return c.resumeRun.CallUnary(ctx, req)
}

// PauseRun calls ironflow.v1.IronflowService.PauseRun.
func (c *ironflowServiceClient) PauseRun(ctx context.Context, req *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error) {
	return c.pauseRun.CallUnary(ctx, req)
}

// GetPausedState calls ironflow.v1.IronflowService.GetPausedState.
func (c *ironflowServiceClient) GetPausedState(ctx context.Context, req *connect.Request[v1.GetPausedStateRequest]) (*connect.Response[v1.GetPausedStateResponse], error) {
	return c.getPausedState.CallUnary(ctx, req)
}

// InjectStepOutput calls ironflow.v1.IronflowService.InjectStepOutput.
func (c *ironflowServiceClient) InjectStepOutput(ctx context.Context, req *connect.Request[v1.InjectStepOutputRequest]) (*connect.Response[v1.InjectStepOutputResponse], error) {
	return c.injectStepOutput.CallUnary(ctx, req)
}

// Health calls ironflow.v1.IronflowService.Health.
func (c *ironflowServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Info calls ironflow.v1.IronflowService.Info.
func (c *ironflowServiceClient) Info(ctx context.Context, req *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// IronflowServiceHandler is an implementation of the ironflow.v1.IronflowService service.
type IronflowServiceHandler interface {
	// Register or update a function definition
	RegisterFunction(context.Context, *connect.Request[v1.RegisterFunctionRequest]) (*connect.Response[v1.RegisterFunctionResponse], error)
	// Get a function by ID
	GetFunction(context.Context, *connect.Request[v1.GetFunctionRequest]) (*connect.Response[v1.Function], error)
	// List all registered functions
	ListFunctions(context.Context, *connect.Request[v1.ListFunctionsRequest]) (*connect.Response[v1.ListFunctionsResponse], error)
	// Update function status (pause, activate, archive)
	UpdateFunctionStatus(context.Context, *connect.Request[v1.UpdateFunctionStatusRequest]) (*connect.Response[v1.Function], error)
	// Delete a function
	DeleteFunction(context.Context, *connect.Request[v1.DeleteFunctionRequest]) (*connect.Response[emptypb.Empty], error)
	// List function configuration history
	ListFunctionHistory(context.Context, *connect.Request[v1.ListFunctionHistoryRequest]) (*connect.Response[v1.ListFunctionHistoryResponse], error)
	// Get function configuration at a specific version
	GetFunctionAtVersion(context.Context, *connect.Request[v1.GetFunctionAtVersionRequest]) (*connect.Response[v1.GetFunctionAtVersionResponse], error)
	// Roll back a function to a previous version
	RollbackFunction(context.Context, *connect.Request[v1.RollbackFunctionRequest]) (*connect.Response[v1.RollbackFunctionResponse], error)
	// Trigger an event (async by default)
	Trigger(context.Context, *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error)
	// Emit an event (alias for Trigger with emit semantics)
	Emit(context.Context, *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error)
	// Trigger and wait for completion (sync)
	TriggerSync(context.Context, *connect.Request[v1.TriggerSyncRequest]) (*connect.Response[v1.TriggerSyncResponse], error)
	// Batch trigger multiple events
	TriggerBatch(context.Context, *connect.Request[v1.TriggerBatchRequest]) (*connect.Response[v1.TriggerBatchResponse], error)
	// Get a run by ID
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error)
	// List runs with filtering
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	// Get steps for a run
	GetRunSteps(context.Context, *connect.Request[v1.GetRunStepsRequest]) (*connect.Response[v1.GetRunStepsResponse], error)
	// Cancel a running workflow
	CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.Run], error)
	// Patch a step's output
	PatchStep(context.Context, *connect.Request[v1.PatchStepRequest]) (*connect.Response[v1.Step], error)
	// Resume a paused/failed run
	ResumeRun(context.Context, *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.Run], error)
	// Request a running workflow to pause at the next step boundary
	PauseRun(context.Context, *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error)
	// Get the paused state of a run including completed steps
	GetPausedState(context.Context, *connect.Request[v1.GetPausedStateRequest]) (*connect.Response[v1.GetPausedStateResponse], error)
	// Inject a modified output for a completed step
	InjectStepOutput(context.Context, *connect.Request[v1.InjectStepOutputRequest]) (*connect.Response[v1.InjectStepOutputResponse], error)
	// Health check
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
	// Server info
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
}

// NewIronflowServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIronflowServiceHandler(svc IronflowServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ironflowServiceMethods := v1.File_ironflow_v1_ironflow_proto.Services().ByName("IronflowService").Methods()
	ironflowServiceRegisterFunctionHandler := connect.NewUnaryHandler(
		IronflowServiceRegisterFunctionProcedure,
		svc.RegisterFunction,
		connect.WithSchema(ironflowServiceMethods.ByName("RegisterFunction")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceGetFunctionHandler := connect.NewUnaryHandler(
		IronflowServiceGetFunctionProcedure,
		svc.GetFunction,
		connect.WithSchema(ironflowServiceMethods.ByName("GetFunction")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceListFunctionsHandler := connect.NewUnaryHandler(
		IronflowServiceListFunctionsProcedure,
		svc.ListFunctions,
		connect.WithSchema(ironflowServiceMethods.ByName("ListFunctions")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceUpdateFunctionStatusHandler := connect.NewUnaryHandler(
		IronflowServiceUpdateFunctionStatusProcedure,
		svc.UpdateFunctionStatus,
		connect.WithSchema(ironflowServiceMethods.ByName("UpdateFunctionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceDeleteFunctionHandler := connect.NewUnaryHandler(
		IronflowServiceDeleteFunctionProcedure,
		svc.DeleteFunction,
		connect.WithSchema(ironflowServiceMethods.ByName("DeleteFunction")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceListFunctionHistoryHandler := connect.NewUnaryHandler(
		IronflowServiceListFunctionHistoryProcedure,
		svc.ListFunctionHistory,
		connect.WithSchema(ironflowServiceMethods.ByName("ListFunctionHistory")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceGetFunctionAtVersionHandler := connect.NewUnaryHandler(
		IronflowServiceGetFunctionAtVersionProcedure,
		svc.GetFunctionAtVersion,
		connect.WithSchema(ironflowServiceMethods.ByName("GetFunctionAtVersion")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceRollbackFunctionHandler := connect.NewUnaryHandler(
		IronflowServiceRollbackFunctionProcedure,
		svc.RollbackFunction,
		connect.WithSchema(ironflowServiceMethods.ByName("RollbackFunction")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceTriggerHandler := connect.NewUnaryHandler(
		IronflowServiceTriggerProcedure,
		svc.Trigger,
		connect.WithSchema(ironflowServiceMethods.ByName("Trigger")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceEmitHandler := connect.NewUnaryHandler(
		IronflowServiceEmitProcedure,
		svc.Emit,
		connect.WithSchema(ironflowServiceMethods.ByName("Emit")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceTriggerSyncHandler := connect.NewUnaryHandler(
		IronflowServiceTriggerSyncProcedure,
		svc.TriggerSync,
		connect.WithSchema(ironflowServiceMethods.ByName("TriggerSync")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceTriggerBatchHandler := connect.NewUnaryHandler(
		IronflowServiceTriggerBatchProcedure,
		svc.TriggerBatch,
		connect.WithSchema(ironflowServiceMethods.ByName("TriggerBatch")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceGetRunHandler := connect.NewUnaryHandler(
		IronflowServiceGetRunProcedure,
		svc.GetRun,
		connect.WithSchema(ironflowServiceMethods.ByName("GetRun")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceListRunsHandler := connect.NewUnaryHandler(
		IronflowServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(ironflowServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceGetRunStepsHandler := connect.NewUnaryHandler(
		IronflowServiceGetRunStepsProcedure,
		svc.GetRunSteps,
		connect.WithSchema(ironflowServiceMethods.ByName("GetRunSteps")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceCancelRunHandler := connect.NewUnaryHandler(
		IronflowServiceCancelRunProcedure,
		svc.CancelRun,
		connect.WithSchema(ironflowServiceMethods.ByName("CancelRun")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServicePatchStepHandler := connect.NewUnaryHandler(
		IronflowServicePatchStepProcedure,
		svc.PatchStep,
		connect.WithSchema(ironflowServiceMethods.ByName("PatchStep")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceResumeRunHandler := connect.NewUnaryHandler(
		IronflowServiceResumeRunProcedure,
		svc.ResumeRun,
		connect.WithSchema(ironflowServiceMethods.ByName("ResumeRun")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServicePauseRunHandler := connect.NewUnaryHandler(
		IronflowServicePauseRunProcedure,
		svc.PauseRun,
		connect.WithSchema(ironflowServiceMethods.ByName("PauseRun")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceGetPausedStateHandler := connect.NewUnaryHandler(
		IronflowServiceGetPausedStateProcedure,
		svc.GetPausedState,
		connect.WithSchema(ironflowServiceMethods.ByName("GetPausedState")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceInjectStepOutputHandler := connect.NewUnaryHandler(
		IronflowServiceInjectStepOutputProcedure,
		svc.InjectStepOutput,
		connect.WithSchema(ironflowServiceMethods.ByName("InjectStepOutput")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceHealthHandler := connect.NewUnaryHandler(
		IronflowServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(ironflowServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	ironflowServiceInfoHandler := connect.NewUnaryHandler(
		IronflowServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(ironflowServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ironflow.v1.IronflowService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IronflowServiceRegisterFunctionProcedure:
			ironflowServiceRegisterFunctionHandler.ServeHTTP(w, r)
		case IronflowServiceGetFunctionProcedure:
			ironflowServiceGetFunctionHandler.ServeHTTP(w, r)
		case IronflowServiceListFunctionsProcedure:
			ironflowServiceListFunctionsHandler.ServeHTTP(w, r)
		case IronflowServiceUpdateFunctionStatusProcedure:
			ironflowServiceUpdateFunctionStatusHandler.ServeHTTP(w, r)
		case IronflowServiceDeleteFunctionProcedure:
			ironflowServiceDeleteFunctionHandler.ServeHTTP(w, r)
		case IronflowServiceListFunctionHistoryProcedure:
			ironflowServiceListFunctionHistoryHandler.ServeHTTP(w, r)
		case IronflowServiceGetFunctionAtVersionProcedure:
			ironflowServiceGetFunctionAtVersionHandler.ServeHTTP(w, r)
		case IronflowServiceRollbackFunctionProcedure:
			ironflowServiceRollbackFunctionHandler.ServeHTTP(w, r)
		case IronflowServiceTriggerProcedure:
			ironflowServiceTriggerHandler.ServeHTTP(w, r)
		case IronflowServiceEmitProcedure:
			ironflowServiceEmitHandler.ServeHTTP(w, r)
		case IronflowServiceTriggerSyncProcedure:
			ironflowServiceTriggerSyncHandler.ServeHTTP(w, r)
		case IronflowServiceTriggerBatchProcedure:
			ironflowServiceTriggerBatchHandler.ServeHTTP(w, r)
		case IronflowServiceGetRunProcedure:
			ironflowServiceGetRunHandler.ServeHTTP(w, r)
		case IronflowServiceListRunsProcedure:
			ironflowServiceListRunsHandler.ServeHTTP(w, r)
		case IronflowServiceGetRunStepsProcedure:
			ironflowServiceGetRunStepsHandler.ServeHTTP(w, r)
		case IronflowServiceCancelRunProcedure:
			ironflowServiceCancelRunHandler.ServeHTTP(w, r)
		case IronflowServicePatchStepProcedure:
			ironflowServicePatchStepHandler.ServeHTTP(w, r)
		case IronflowServiceResumeRunProcedure:
			ironflowServiceResumeRunHandler.ServeHTTP(w, r)
		case IronflowServicePauseRunProcedure:
			ironflowServicePauseRunHandler.ServeHTTP(w, r)
		case IronflowServiceGetPausedStateProcedure:
			ironflowServiceGetPausedStateHandler.ServeHTTP(w, r)
		case IronflowServiceInjectStepOutputProcedure:
			ironflowServiceInjectStepOutputHandler.ServeHTTP(w, r)
		case IronflowServiceHealthProcedure:
			ironflowServiceHealthHandler.ServeHTTP(w, r)
		case IronflowServiceInfoProcedure:
			ironflowServiceInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIronflowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIronflowServiceHandler struct{}

func (UnimplementedIronflowServiceHandler) RegisterFunction(context.Context, *connect.Request[v1.RegisterFunctionRequest]) (*connect.Response[v1.RegisterFunctionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.RegisterFunction is not implemented"))
}

func (UnimplementedIronflowServiceHandler) GetFunction(context.Context, *connect.Request[v1.GetFunctionRequest]) (*connect.Response[v1.Function], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.GetFunction is not implemented"))
}

func (UnimplementedIronflowServiceHandler) ListFunctions(context.Context, *connect.Request[v1.ListFunctionsRequest]) (*connect.Response[v1.ListFunctionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.ListFunctions is not implemented"))
}

func (UnimplementedIronflowServiceHandler) UpdateFunctionStatus(context.Context, *connect.Request[v1.UpdateFunctionStatusRequest]) (*connect.Response[v1.Function], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.UpdateFunctionStatus is not implemented"))
}

func (UnimplementedIronflowServiceHandler) DeleteFunction(context.Context, *connect.Request[v1.DeleteFunctionRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.DeleteFunction is not implemented"))
}

func (UnimplementedIronflowServiceHandler) ListFunctionHistory(context.Context, *connect.Request[v1.ListFunctionHistoryRequest]) (*connect.Response[v1.ListFunctionHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.ListFunctionHistory is not implemented"))
}

func (UnimplementedIronflowServiceHandler) GetFunctionAtVersion(context.Context, *connect.Request[v1.GetFunctionAtVersionRequest]) (*connect.Response[v1.GetFunctionAtVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.GetFunctionAtVersion is not implemented"))
}

func (UnimplementedIronflowServiceHandler) RollbackFunction(context.Context, *connect.Request[v1.RollbackFunctionRequest]) (*connect.Response[v1.RollbackFunctionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.RollbackFunction is not implemented"))
}

func (UnimplementedIronflowServiceHandler) Trigger(context.Context, *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.Trigger is not implemented"))
}

func (UnimplementedIronflowServiceHandler) Emit(context.Context, *connect.Request[v1.TriggerRequest]) (*connect.Response[v1.TriggerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.Emit is not implemented"))
}

func (UnimplementedIronflowServiceHandler) TriggerSync(context.Context, *connect.Request[v1.TriggerSyncRequest]) (*connect.Response[v1.TriggerSyncResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.TriggerSync is not implemented"))
}

func (UnimplementedIronflowServiceHandler) TriggerBatch(context.Context, *connect.Request[v1.TriggerBatchRequest]) (*connect.Response[v1.TriggerBatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.TriggerBatch is not implemented"))
}

func (UnimplementedIronflowServiceHandler) GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.Run], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.GetRun is not implemented"))
}

func (UnimplementedIronflowServiceHandler) ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.ListRuns is not implemented"))
}

func (UnimplementedIronflowServiceHandler) GetRunSteps(context.Context, *connect.Request[v1.GetRunStepsRequest]) (*connect.Response[v1.GetRunStepsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.GetRunSteps is not implemented"))
}

func (UnimplementedIronflowServiceHandler) CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.Run], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.CancelRun is not implemented"))
}

func (UnimplementedIronflowServiceHandler) PatchStep(context.Context, *connect.Request[v1.PatchStepRequest]) (*connect.Response[v1.Step], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.PatchStep is not implemented"))
}

func (UnimplementedIronflowServiceHandler) ResumeRun(context.Context, *connect.Request[v1.ResumeRunRequest]) (*connect.Response[v1.Run], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.ResumeRun is not implemented"))
}

func (UnimplementedIronflowServiceHandler) PauseRun(context.Context, *connect.Request[v1.PauseRunRequest]) (*connect.Response[v1.PauseRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.PauseRun is not implemented"))
}

func (UnimplementedIronflowServiceHandler) GetPausedState(context.Context, *connect.Request[v1.GetPausedStateRequest]) (*connect.Response[v1.GetPausedStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.GetPausedState is not implemented"))
}

func (UnimplementedIronflowServiceHandler) InjectStepOutput(context.Context, *connect.Request[v1.InjectStepOutputRequest]) (*connect.Response[v1.InjectStepOutputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.InjectStepOutput is not implemented"))
}

func (UnimplementedIronflowServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.Health is not implemented"))
}

func (UnimplementedIronflowServiceHandler) Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.IronflowService.Info is not implemented"))
}
