// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ironflow/v1/timetravel.proto

package ironflowv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sahina/ironflow-go/api/ironflow/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TimeTravelServiceName is the fully-qualified name of the TimeTravelService service.
	TimeTravelServiceName = "ironflow.v1.TimeTravelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TimeTravelServiceGetRunStateAtProcedure is the fully-qualified name of the TimeTravelService's
	// GetRunStateAt RPC.
	TimeTravelServiceGetRunStateAtProcedure = "/ironflow.v1.TimeTravelService/GetRunStateAt"
	// TimeTravelServiceGetRunTimelineProcedure is the fully-qualified name of the TimeTravelService's
	// GetRunTimeline RPC.
	TimeTravelServiceGetRunTimelineProcedure = "/ironflow.v1.TimeTravelService/GetRunTimeline"
	// TimeTravelServiceGetStepOutputAtProcedure is the fully-qualified name of the TimeTravelService's
	// GetStepOutputAt RPC.
	TimeTravelServiceGetStepOutputAtProcedure = "/ironflow.v1.TimeTravelService/GetStepOutputAt"
)

// TimeTravelServiceClient is a client for the ironflow.v1.TimeTravelService service.
type TimeTravelServiceClient interface {
	GetRunStateAt(context.Context, *connect.Request[v1.GetRunStateAtRequest]) (*connect.Response[v1.GetRunStateAtResponse], error)
	GetRunTimeline(context.Context, *connect.Request[v1.GetRunTimelineRequest]) (*connect.Response[v1.GetRunTimelineResponse], error)
	GetStepOutputAt(context.Context, *connect.Request[v1.GetStepOutputAtRequest]) (*connect.Response[v1.GetStepOutputAtResponse], error)
}

// NewTimeTravelServiceClient constructs a client for the ironflow.v1.TimeTravelService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTimeTravelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TimeTravelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	timeTravelServiceMethods := v1.File_ironflow_v1_timetravel_proto.Services().ByName("TimeTravelService").Methods()
	return &timeTravelServiceClient{
		getRunStateAt: connect.NewClient[v1.GetRunStateAtRequest, v1.GetRunStateAtResponse](
			httpClient,
			baseURL+TimeTravelServiceGetRunStateAtProcedure,
			connect.WithSchema(timeTravelServiceMethods.ByName("GetRunStateAt")),
			connect.WithClientOptions(opts...),
		),
		getRunTimeline: connect.NewClient[v1.GetRunTimelineRequest, v1.GetRunTimelineResponse](
			httpClient,
			baseURL+TimeTravelServiceGetRunTimelineProcedure,
			connect.WithSchema(timeTravelServiceMethods.ByName("GetRunTimeline")),
			connect.WithClientOptions(opts...),
		),
		getStepOutputAt: connect.NewClient[v1.GetStepOutputAtRequest, v1.GetStepOutputAtResponse](
			httpClient,
			baseURL+TimeTravelServiceGetStepOutputAtProcedure,
			connect.WithSchema(timeTravelServiceMethods.ByName("GetStepOutputAt")),
			connect.WithClientOptions(opts...),
		),
	}
}

// timeTravelServiceClient implements TimeTravelServiceClient.
type timeTravelServiceClient struct {
	getRunStateAt   *connect.Client[v1.GetRunStateAtRequest, v1.GetRunStateAtResponse]
	getRunTimeline  *connect.Client[v1.GetRunTimelineRequest, v1.GetRunTimelineResponse]
	getStepOutputAt *connect.Client[v1.GetStepOutputAtRequest, v1.GetStepOutputAtResponse]
}

// GetRunStateAt calls ironflow.v1.TimeTravelService.GetRunStateAt.
func (c *timeTravelServiceClient) GetRunStateAt(ctx context.Context, req *connect.Request[v1.GetRunStateAtRequest]) (*connect.Response[v1.GetRunStateAtResponse], error) {
	return c.getRunStateAt.CallUnary(ctx, req)
}

// GetRunTimeline calls ironflow.v1.TimeTravelService.GetRunTimeline.
func (c *timeTravelServiceClient) GetRunTimeline(ctx context.Context, req *connect.Request[v1.GetRunTimelineRequest]) (*connect.Response[v1.GetRunTimelineResponse], error) {
	return c.getRunTimeline.CallUnary(ctx, req)
}

// GetStepOutputAt calls ironflow.v1.TimeTravelService.GetStepOutputAt.
func (c *timeTravelServiceClient) GetStepOutputAt(ctx context.Context, req *connect.Request[v1.GetStepOutputAtRequest]) (*connect.Response[v1.GetStepOutputAtResponse], error) {
	return c.getStepOutputAt.CallUnary(ctx, req)
}

// TimeTravelServiceHandler is an implementation of the ironflow.v1.TimeTravelService service.
type TimeTravelServiceHandler interface {
	GetRunStateAt(context.Context, *connect.Request[v1.GetRunStateAtRequest]) (*connect.Response[v1.GetRunStateAtResponse], error)
	GetRunTimeline(context.Context, *connect.Request[v1.GetRunTimelineRequest]) (*connect.Response[v1.GetRunTimelineResponse], error)
	GetStepOutputAt(context.Context, *connect.Request[v1.GetStepOutputAtRequest]) (*connect.Response[v1.GetStepOutputAtResponse], error)
}

// NewTimeTravelServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTimeTravelServiceHandler(svc TimeTravelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	timeTravelServiceMethods := v1.File_ironflow_v1_timetravel_proto.Services().ByName("TimeTravelService").Methods()
	timeTravelServiceGetRunStateAtHandler := connect.NewUnaryHandler(
		TimeTravelServiceGetRunStateAtProcedure,
		svc.GetRunStateAt,
		connect.WithSchema(timeTravelServiceMethods.ByName("GetRunStateAt")),
		connect.WithHandlerOptions(opts...),
	)
	timeTravelServiceGetRunTimelineHandler := connect.NewUnaryHandler(
		TimeTravelServiceGetRunTimelineProcedure,
		svc.GetRunTimeline,
		connect.WithSchema(timeTravelServiceMethods.ByName("GetRunTimeline")),
		connect.WithHandlerOptions(opts...),
	)
	timeTravelServiceGetStepOutputAtHandler := connect.NewUnaryHandler(
		TimeTravelServiceGetStepOutputAtProcedure,
		svc.GetStepOutputAt,
		connect.WithSchema(timeTravelServiceMethods.ByName("GetStepOutputAt")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ironflow.v1.TimeTravelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TimeTravelServiceGetRunStateAtProcedure:
			timeTravelServiceGetRunStateAtHandler.ServeHTTP(w, r)
		case TimeTravelServiceGetRunTimelineProcedure:
			timeTravelServiceGetRunTimelineHandler.ServeHTTP(w, r)
		case TimeTravelServiceGetStepOutputAtProcedure:
			timeTravelServiceGetStepOutputAtHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTimeTravelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTimeTravelServiceHandler struct{}

func (UnimplementedTimeTravelServiceHandler) GetRunStateAt(context.Context, *connect.Request[v1.GetRunStateAtRequest]) (*connect.Response[v1.GetRunStateAtResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.TimeTravelService.GetRunStateAt is not implemented"))
}

func (UnimplementedTimeTravelServiceHandler) GetRunTimeline(context.Context, *connect.Request[v1.GetRunTimelineRequest]) (*connect.Response[v1.GetRunTimelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.TimeTravelService.GetRunTimeline is not implemented"))
}

func (UnimplementedTimeTravelServiceHandler) GetStepOutputAt(context.Context, *connect.Request[v1.GetStepOutputAtRequest]) (*connect.Response[v1.GetStepOutputAtResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ironflow.v1.TimeTravelService.GetStepOutputAt is not implemented"))
}
